//! Explicit conservative fusion of dispatch invocations.
//!
//! An [`Invocation`] is a prepared kernel plus its actual arguments and dispatch grid.
//! [`FusedKernel`] lowers compatible invocations of generated kernels to one physical
//! dispatch that preserves every parcel load and store of the unfused sequence.

use super::prepare::{access_kind_to_node, prepare_kernel_as};
use super::{KernelBindable, KernelDef, KernelParam, PreparedKernel, RecordedDispatch, SchemeNodeStart};
use crate::backend::shared::{MAX_BINDLESS_SLOTS, MAX_USER_SLOTS};
use crate::error::GoldyError;
use crate::runtime::Runtime;
use crate::scheme::Scheme;
use crate::shader::KernelIdentity;
use crate::task_graph::analysis::resources_alias;
use crate::task_graph::ResourceId;
use goldy_shader_ir::{
    compose, AccessKind, FusedDefinition, FusionLimits, FusionRejection, FusionStage, KernelId,
    PORTABLE_WORKGROUP_BYTES,
};

const LIMITS: FusionLimits = FusionLimits {
    resources: MAX_BINDLESS_SLOTS,
    scalars: MAX_USER_SLOTS,
    workgroup_bytes: PORTABLE_WORKGROUP_BYTES,
};

#[derive(Clone, Copy)]
enum KernelArg<'a> {
    Resource(&'a dyn KernelBindable),
    /// Wire word (`f32` via `to_bits`, etc.).
    Scalar(u32),
}

/// Actual arguments of an [`Invocation`], in declaration order, awaiting a grid.
///
/// Generated kernels expose `invoke(args..)`; this builder is the untyped form.
pub struct InvocationBuilder<'a> {
    kernel: &'a PreparedKernel,
    args: Vec<KernelArg<'a>>,
}

impl PreparedKernel {
    /// Begin an [`Invocation`] of this kernel (untyped escape hatch).
    ///
    /// Prefer the typed `invoke` method generated by `#[goldy::compute]`.
    pub fn invoke(&self) -> InvocationBuilder<'_> {
        InvocationBuilder {
            kernel: self,
            args: Vec::new(),
        }
    }
}

impl<'a> InvocationBuilder<'a> {
    /// Bind the next formal, a resource.
    pub fn resource(mut self, resource: &'a dyn KernelBindable) -> Self {
        self.args.push(KernelArg::Resource(resource));
        self
    }

    /// Bind the next formal, a scalar wire word.
    pub fn bind_u32(mut self, value: u32) -> Self {
        self.args.push(KernelArg::Scalar(value));
        self
    }

    pub fn bind_i32(self, value: i32) -> Self {
        self.bind_u32(value as u32)
    }

    pub fn bind_f32(self, value: f32) -> Self {
        self.bind_u32(value.to_bits())
    }

    pub fn bind_bool(self, value: bool) -> Self {
        self.bind_u32(u32::from(value))
    }

    /// Exact workgroup counts.
    pub fn groups(self, counts: [u32; 3]) -> Invocation<'a> {
        Invocation {
            kernel: self.kernel,
            args: self.args,
            groups: counts,
        }
    }

    /// Cover `n` threads in 1D using the kernel's fixed workgroup size.
    pub fn over_1d(self, n: u32) -> Invocation<'a> {
        let [wx, ..] = self.kernel.workgroup_size();
        self.groups([n.div_ceil(wx.max(1)), 1, 1])
    }

    /// Cover a 2D thread extent.
    pub fn over_2d(self, width: u32, height: u32) -> Invocation<'a> {
        let [wx, wy, _] = self.kernel.workgroup_size();
        self.groups([width.div_ceil(wx.max(1)), height.div_ceil(wy.max(1)), 1])
    }

    /// Cover a 3D thread extent.
    pub fn over_3d(self, width: u32, height: u32, depth: u32) -> Invocation<'a> {
        let [wx, wy, wz] = self.kernel.workgroup_size();
        self.groups([
            width.div_ceil(wx.max(1)),
            height.div_ceil(wy.max(1)),
            depth.div_ceil(wz.max(1)),
        ])
    }
}

/// A dispatch as a value: prepared kernel, actual arguments and grid.
///
/// Record it on its own with [`Self::record`], or lower several to one dispatch with
/// [`FusedKernel`].
#[derive(Clone)]
pub struct Invocation<'a> {
    kernel: &'a PreparedKernel,
    args: Vec<KernelArg<'a>>,
    groups: [u32; 3],
}

impl<'a> Invocation<'a> {
    pub fn kernel(&self) -> &'a PreparedKernel {
        self.kernel
    }

    pub fn groups(&self) -> [u32; 3] {
        self.groups
    }

    /// Record this invocation as its own dispatch node.
    pub fn record(
        &self,
        scheme: &mut Scheme,
        label: impl Into<crate::SchemeLabel>,
    ) -> Result<RecordedDispatch, GoldyError> {
        let def = self.kernel.def();
        if def.params.iter().any(|p| p.is_tensor) {
            return Err(GoldyError::Validation(format!(
                "kernel `{}`: invocations do not bind tensor parameters yet; use the generated `record`",
                def.entry
            )));
        }
        if let Some(reason) = arity_mismatch(&def.params, &self.args) {
            return Err(GoldyError::Validation(format!(
                "kernel `{}` invocation: {reason}",
                def.entry
            )));
        }
        let mut start = self.kernel.begin_record(scheme, label);
        for (param, arg) in def.params.iter().zip(&self.args) {
            start = bind(start, param, arg);
        }
        Ok(start.finish().groups(self.groups))
    }
}

fn arity_mismatch(params: &[KernelParam], args: &[KernelArg<'_>]) -> Option<String> {
    if params.len() != args.len() {
        return Some(format!("{} formals, {} arguments", params.len(), args.len()));
    }
    params.iter().zip(args).find_map(|(p, a)| {
        let resource_arg = matches!(a, KernelArg::Resource(_));
        (p.category.is_resource() != resource_arg).then(|| {
            format!(
                "`{}` expects a {} argument",
                p.name,
                if resource_arg { "scalar" } else { "resource" }
            )
        })
    })
}

fn bind<'s>(start: SchemeNodeStart<'s>, param: &KernelParam, arg: &KernelArg<'_>) -> SchemeNodeStart<'s> {
    match arg {
        KernelArg::Resource(r) => {
            let access = param.access.expect("resource formals declare an access");
            r.__goldy_bind_kernel(start, access_kind_to_node(access))
        }
        KernelArg::Scalar(word) => start.bind_u32(*word),
    }
}

/// Why [`FusedKernel::prepare`] produced no fused kernel. Record the invocations
/// unfused instead.
#[derive(Debug, thiserror::Error)]
pub enum FusionError {
    #[error("fusion rejected: {0}")]
    Rejected(#[from] FusionRejection),
    #[error("fused kernel failed to compile: {0:#}")]
    Compile(anyhow::Error),
}

impl From<FusionError> for GoldyError {
    fn from(e: FusionError) -> Self {
        match e {
            FusionError::Rejected(r) => GoldyError::Validation(format!("fusion rejected: {r}")),
            FusionError::Compile(e) => GoldyError::Backend(e),
        }
    }
}

/// One compute pipeline that runs a sequence of invocations as one dispatch.
///
/// Every constituent still loads and stores its parcels, so an intermediate parcel
/// ends in the same state as after the unfused sequence.
pub struct FusedKernel {
    prepared: PreparedKernel,
    definition: FusedDefinition,
}

impl FusedKernel {
    /// Compose `stages` (in execution order) and compile the fused entry.
    ///
    /// The fused pipeline depends on which actual arguments are the same parcel, not on
    /// the parcels themselves; [`Self::record`] accepts any invocations with that shape.
    pub fn prepare(device: &Runtime, stages: &[Invocation<'_>]) -> Result<Self, FusionError> {
        let definition = admit(stages).inspect_err(|reason| {
            tracing::debug!(%reason, "kernel fusion rejected");
        })?;
        let identity = KernelIdentity {
            id: definition.id(),
            scalars: definition.scalar_origins().iter().map(ToString::to_string).collect(),
        };
        let prepared = prepare_kernel_as(device, definition.lower(), Some(identity)).map_err(FusionError::Compile)?;
        tracing::debug!(
            kernel = %definition.name,
            id = %definition.id(),
            stages = definition.stages.len(),
            params = definition.params.len(),
            "kernel fusion prepared"
        );
        Ok(Self { prepared, definition })
    }

    pub fn definition(&self) -> &FusedDefinition {
        &self.definition
    }

    /// Identity of the fused program. Fused kernels with one id share specialized variants.
    pub fn id(&self) -> KernelId {
        self.definition.id()
    }

    /// Scalar slot of the fused dispatch that scalar `formal` of stage `stage` binds, for
    /// [`Scheme::set_node_param`].
    pub fn scalar_slot(&self, stage: usize, formal: &str) -> Option<usize> {
        self.definition.scalar_slot(stage, formal)
    }

    /// Canonical source and ABI of the fused entry.
    pub fn def(&self) -> &KernelDef {
        self.prepared.def()
    }

    pub fn pipeline(&self) -> &crate::ComputePipeline {
        self.prepared.pipeline()
    }

    /// Record `stages` as one dispatch node.
    ///
    /// `stages` must compose to the definition this kernel was prepared from: the same
    /// kernels, grid and sharing of parcels between arguments.
    pub fn record(
        &self,
        scheme: &mut Scheme,
        label: impl Into<crate::SchemeLabel>,
        stages: &[Invocation<'_>],
    ) -> Result<RecordedDispatch, GoldyError> {
        let definition = admit(stages).map_err(FusionError::Rejected)?;
        if definition != self.definition {
            return Err(GoldyError::Validation(format!(
                "fused kernel `{}`: invocations do not compose to the definition it was prepared from",
                self.definition.name
            )));
        }
        let mut start = self.prepared.begin_record(scheme, label);
        for (j, param) in self.definition.params.iter().enumerate() {
            let (k, i) = self
                .definition
                .stages
                .iter()
                .enumerate()
                .find_map(|(k, s)| s.args.iter().position(|&a| a == j).map(|i| (k, i)))
                .expect("every fused parameter is bound by a formal");
            start = bind(start, param, &stages[k].args[i]);
        }
        Ok(start.finish().groups(stages[0].groups))
    }
}

fn admit(stages: &[Invocation<'_>]) -> Result<FusedDefinition, FusionRejection> {
    let first = stages.first().ok_or(FusionRejection::Empty)?;
    let mut definitions = Vec::with_capacity(stages.len());
    for (k, s) in stages.iter().enumerate() {
        let def = s.kernel.def();
        let Some(definition) = &def.definition else {
            return Err(FusionRejection::OpaqueDefinition {
                stage: k,
                kernel: def.entry.clone(),
            });
        };
        if definition.params.iter().any(|p| p.is_tensor) {
            return Err(FusionRejection::Unsupported {
                stage: k,
                kernel: definition.name.clone(),
                reason: "tensor parameters".into(),
            });
        }
        if let Some(reason) = arity_mismatch(&definition.params, &s.args) {
            return Err(FusionRejection::InvalidArgumentMap(format!(
                "stage {k} (`{}`): {reason}",
                definition.name
            )));
        }
        let expected = first.kernel.workgroup_size();
        if def.workgroup_size != expected {
            return Err(FusionRejection::WorkgroupSize {
                stage: k,
                expected,
                got: def.workgroup_size,
            });
        }
        if s.groups != first.groups {
            return Err(FusionRejection::Grid {
                stage: k,
                expected: first.groups,
                got: s.groups,
            });
        }
        definitions.push(definition);
    }

    let args = argument_map(stages, &definitions)?;
    let name = definitions
        .iter()
        .map(|d| d.name.as_str())
        .collect::<Vec<_>>()
        .join("+");
    let fusion: Vec<FusionStage<'_>> = definitions
        .iter()
        .zip(&args)
        .map(|(definition, args)| FusionStage { definition, args })
        .collect();
    let fused = compose(&name, &fusion, &LIMITS)?;

    if let Some(rank) = fused.dependence_rank {
        let threads: [u32; 3] = std::array::from_fn(|a| fused.workgroup_size[a].saturating_mul(first.groups[a]));
        if threads[rank as usize..].iter().any(|&t| t > 1) {
            return Err(FusionRejection::GridRank { rank, threads });
        }
    }
    Ok(fused)
}

/// Fused parameter index of every formal: one per distinct parcel, one per scalar.
fn argument_map(
    stages: &[Invocation<'_>],
    definitions: &[&goldy_shader_ir::ShaderKernel],
) -> Result<Vec<Vec<usize>>, FusionRejection> {
    struct Parcel {
        id: ResourceId,
        fused: usize,
        writes: bool,
        origin: (usize, usize),
    }
    let mut parcels: Vec<Parcel> = Vec::new();
    let mut next = 0;
    let mut maps = Vec::with_capacity(stages.len());
    for (k, (stage, definition)) in stages.iter().zip(definitions).enumerate() {
        let mut map = Vec::with_capacity(stage.args.len());
        for (i, (formal, arg)) in definition.params.iter().zip(&stage.args).enumerate() {
            let KernelArg::Resource(resource) = arg else {
                map.push(next);
                next += 1;
                continue;
            };
            let Some(id) = resource.__goldy_kernel_identity().0 else {
                return Err(FusionRejection::UnknownIdentity {
                    stage: k,
                    formal: formal.name.clone(),
                });
            };
            let writes = formal.access.is_some_and(|a| a != AccessKind::Read);
            match parcels.iter_mut().find(|p| p.id == id) {
                Some(p) => {
                    p.writes |= writes;
                    map.push(p.fused);
                }
                None => {
                    parcels.push(Parcel {
                        id,
                        fused: next,
                        writes,
                        origin: (k, i),
                    });
                    map.push(next);
                    next += 1;
                }
            }
        }
        maps.push(map);
    }
    for (x, a) in parcels.iter().enumerate() {
        if let Some(b) = parcels[x + 1..]
            .iter()
            .find(|b| (a.writes || b.writes) && resources_alias(a.id, b.id))
        {
            let (k, i) = b.origin;
            return Err(FusionRejection::PartialAlias {
                stage: k,
                formal: definitions[k].params[i].name.clone(),
            });
        }
    }
    Ok(maps)
}
