//! Typed Rust compute kernels (`#[goldy::compute]`).
//!
//! The proc-macro frontend lowers a restricted GPU dialect to canonical
//! `[goldy_compute]` Slang plus a structured [`KernelDef`]. Preparation goes
//! through the existing Slang compiler, reflection, and shader cache; recording
//! binds Scheme parcels/scalars from the ABI in declaration order.

mod dispatch;
mod prepare;

pub use dispatch::{DispatchBuilder, RecordedDispatch};
pub use goldy_shader_ir::{
    AccessKind, BuiltinMask, ElementType, KernelDef, KernelParam, KernelSource, ParamCategory, ScalarType, SourceMap,
    KERNEL_ABI_VERSION,
};
pub use prepare::{dump_kernel_artifacts, prepare_kernel, PreparedKernel, SchemeNodeStart};

/// Public binding surface for typed `record` methods generated by `#[goldy::compute]`.
///
/// Implemented for the same types accepted by [`crate::Scheme`]'s `with_parcel`.
pub trait KernelBindable {
    #[doc(hidden)]
    fn __goldy_bind_kernel<'a>(
        &self,
        start: SchemeNodeStart<'a>,
        access: crate::task_graph::NodeAccess,
    ) -> SchemeNodeStart<'a>;
}

macro_rules! impl_kernel_bindable {
    ($($t:ty),+ $(,)?) => {$(
        impl KernelBindable for $t {
            fn __goldy_bind_kernel<'a>(
                &self,
                start: SchemeNodeStart<'a>,
                access: crate::task_graph::NodeAccess,
            ) -> SchemeNodeStart<'a> {
                start.bind_resource(self, access)
            }
        }
    )+};
}

impl_kernel_bindable!(crate::parcel::Parcel, crate::Buffer, crate::Sampler, crate::Texture,);

#[cfg(feature = "graphics")]
impl KernelBindable for crate::PresentLease {
    fn __goldy_bind_kernel<'a>(
        &self,
        start: SchemeNodeStart<'a>,
        access: crate::task_graph::NodeAccess,
    ) -> SchemeNodeStart<'a> {
        start.bind_present(self, access)
    }
}

impl KernelBindable for crate::scheme::Lease<crate::scheme::LeaseTexture> {
    fn __goldy_bind_kernel<'a>(
        &self,
        start: SchemeNodeStart<'a>,
        access: crate::task_graph::NodeAccess,
    ) -> SchemeNodeStart<'a> {
        start.bind_resource(self, access)
    }
}

impl KernelBindable for crate::scheme::Lease<crate::scheme::LeaseBuffer> {
    fn __goldy_bind_kernel<'a>(
        &self,
        start: SchemeNodeStart<'a>,
        access: crate::task_graph::NodeAccess,
    ) -> SchemeNodeStart<'a> {
        start.bind_resource(self, access)
    }
}

/// Marker module for GPU-dialect types and builtins referenced inside
/// `#[goldy::compute]` function signatures and bodies.
///
/// These items exist so host code and docs can name the dialect; the compute
/// proc-macro consumes the AST and does not execute these functions on the CPU.
pub mod gpu {
    /// Write-only buffer parameter (`Scattered<T>` + [`crate::NodeAccess::Write`]).
    #[derive(Debug, Clone, Copy)]
    pub struct Out<T> {
        _marker: core::marker::PhantomData<T>,
    }

    /// Explicit broadcast / uniform buffer parameter.
    #[derive(Debug, Clone, Copy)]
    pub struct Uniform<T> {
        _marker: core::marker::PhantomData<T>,
    }

    /// Write-only storage image (`DirectSpatial<T>`).
    #[derive(Debug, Clone, Copy)]
    pub struct Image<T = Float4> {
        _marker: core::marker::PhantomData<T>,
    }

    /// `float2` in generated Slang.
    #[derive(Debug, Clone, Copy)]
    pub struct Float2 {
        pub x: f32,
        pub y: f32,
    }

    /// `float3` in generated Slang.
    #[derive(Debug, Clone, Copy)]
    pub struct Float3 {
        pub x: f32,
        pub y: f32,
        pub z: f32,
    }

    /// `float4` in generated Slang.
    #[derive(Debug, Clone, Copy)]
    pub struct Float4 {
        pub x: f32,
        pub y: f32,
        pub z: f32,
        pub w: f32,
    }

    /// 3-component thread index (maps to `ThreadId` / `SV_DispatchThreadID`).
    #[derive(Debug, Clone, Copy)]
    pub struct UVec3 {
        pub x: u32,
        pub y: u32,
        pub z: u32,
    }

    /// Global dispatch thread id (`gpu::global_id()`).
    pub fn global_id() -> UVec3 {
        unimplemented!("gpu::global_id is only valid inside #[goldy::compute] bodies")
    }

    /// Workgroup-local thread id (`gpu::local_id()`).
    pub fn local_id() -> UVec3 {
        unimplemented!("gpu::local_id is only valid inside #[goldy::compute] bodies")
    }

    /// Workgroup id (`gpu::workgroup_id()`).
    pub fn workgroup_id() -> UVec3 {
        unimplemented!("gpu::workgroup_id is only valid inside #[goldy::compute] bodies")
    }

    pub fn float2(_x: f32, _y: f32) -> Float2 {
        unimplemented!("gpu::float2 is only valid inside #[goldy::compute] bodies")
    }

    pub fn float3(_x: f32, _y: f32, _z: f32) -> Float3 {
        unimplemented!("gpu::float3 is only valid inside #[goldy::compute] bodies")
    }

    pub fn float4(_x: f32, _y: f32, _z: f32, _w: f32) -> Float4 {
        unimplemented!("gpu::float4 is only valid inside #[goldy::compute] bodies")
    }

    pub fn uint2(_x: u32, _y: u32) -> UVec3 {
        unimplemented!("gpu::uint2 is only valid inside #[goldy::compute] bodies")
    }

    pub fn sin(_x: f32) -> f32 {
        unimplemented!("gpu::sin is only valid inside #[goldy::compute] bodies")
    }

    pub fn length(_v: Float2) -> f32 {
        unimplemented!("gpu::length is only valid inside #[goldy::compute] bodies")
    }
}
