//! Typed Rust compute kernels (`#[goldy::compute]`).
//!
//! The proc-macro frontend lowers a restricted GPU dialect to canonical
//! `[goldy_compute]` Slang plus a structured [`KernelDef`]. Preparation goes
//! through the existing Slang compiler, reflection, and shader cache; recording
//! binds Scheme parcels/scalars from the ABI in declaration order.

mod dispatch;
mod prepare;

pub use dispatch::{DispatchBuilder, RecordedDispatch};
pub use goldy_shader_ir::{
    AccessKind, BuiltinMask, ElementType, KernelDef, KernelParam, KernelSource, ParamCategory, ScalarType, SourceMap,
    KERNEL_ABI_VERSION,
};
pub use prepare::{dump_kernel_artifacts, prepare_kernel, PreparedKernel, SchemeNodeStart};

/// Public binding surface for typed `record` methods generated by `#[goldy::compute]`.
///
/// Implemented for the same types accepted by [`crate::Scheme`]'s `with_parcel`.
pub trait KernelBindable {
    #[doc(hidden)]
    fn __goldy_bind_kernel<'a>(
        &self,
        start: SchemeNodeStart<'a>,
        access: crate::task_graph::NodeAccess,
    ) -> SchemeNodeStart<'a>;
}

macro_rules! impl_kernel_bindable {
    ($($t:ty),+ $(,)?) => {$(
        impl KernelBindable for $t {
            fn __goldy_bind_kernel<'a>(
                &self,
                start: SchemeNodeStart<'a>,
                access: crate::task_graph::NodeAccess,
            ) -> SchemeNodeStart<'a> {
                start.bind_resource(self, access)
            }
        }
    )+};
}

impl_kernel_bindable!(crate::parcel::Parcel, crate::Buffer, crate::Sampler, crate::Texture,);

impl<T> KernelBindable for crate::scheme::Lease<T> {
    fn __goldy_bind_kernel<'a>(
        &self,
        start: SchemeNodeStart<'a>,
        access: crate::task_graph::NodeAccess,
    ) -> SchemeNodeStart<'a> {
        start.bind_resource(self, access)
    }
}

/// Marker module for GPU-dialect types and builtins referenced inside
/// `#[goldy::compute]` function signatures and bodies.
///
/// These items exist so host code and docs can name the dialect; the compute
/// proc-macro consumes the AST and does not execute these functions on the CPU.
pub mod gpu {
    /// Write-only buffer parameter (`Scattered<T>` + [`crate::NodeAccess::Write`]).
    #[derive(Debug, Clone, Copy)]
    pub struct Out<T> {
        _marker: core::marker::PhantomData<T>,
    }

    /// Explicit broadcast / uniform buffer parameter.
    #[derive(Debug, Clone, Copy)]
    pub struct Uniform<T> {
        _marker: core::marker::PhantomData<T>,
    }

    /// 3-component thread index (maps to `ThreadId` / `SV_DispatchThreadID`).
    #[derive(Debug, Clone, Copy)]
    pub struct UVec3 {
        pub x: u32,
        pub y: u32,
        pub z: u32,
    }

    /// Global dispatch thread id (`gpu::global_id()`).
    pub fn global_id() -> UVec3 {
        unimplemented!("gpu::global_id is only valid inside #[goldy::compute] bodies")
    }

    /// Workgroup-local thread id (`gpu::local_id()`).
    pub fn local_id() -> UVec3 {
        unimplemented!("gpu::local_id is only valid inside #[goldy::compute] bodies")
    }

    /// Workgroup id (`gpu::workgroup_id()`).
    pub fn workgroup_id() -> UVec3 {
        unimplemented!("gpu::workgroup_id is only valid inside #[goldy::compute] bodies")
    }
}
