//! Prepare a [`KernelDef`] into a device-scoped compute pipeline.

use crate::compute::ComputePipeline;
use crate::device::Device;
use crate::kernel::{DispatchBuilder, KernelDef};
use crate::scheme::{Scheme, SchemeBindable};
use crate::shader::ShaderModule;
use crate::task_graph::NodeAccess;
use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;
use std::sync::Arc;

/// Device-scoped prepared kernel: compiled pipeline + ABI metadata.
pub struct PreparedKernel {
    pipeline: Arc<ComputePipeline>,
    def: KernelDef,
}

impl PreparedKernel {
    pub fn pipeline(&self) -> &ComputePipeline {
        &self.pipeline
    }

    pub fn def(&self) -> &KernelDef {
        &self.def
    }

    pub fn workgroup_size(&self) -> [u32; 3] {
        self.def.workgroup_size
    }

    /// Begin a Scheme node for this kernel (untyped escape hatch).
    ///
    /// Prefer the typed `record` method generated by `#[goldy::compute]`.
    pub fn begin_record<'a>(&'a self, scheme: &'a mut Scheme, label: &'static str) -> SchemeNodeStart<'a> {
        SchemeNodeStart {
            builder: scheme.node(label, self.pipeline.as_ref()),
            workgroup_size: self.def.workgroup_size,
            def: &self.def,
            resource_i: 0,
            scalar_i: 0,
        }
    }
}

/// Helper used by generated `record` methods to bind ABI-ordered arguments.
pub struct SchemeNodeStart<'a> {
    builder: crate::scheme::SchemeNodeBuilder<'a>,
    workgroup_size: [u32; 3],
    def: &'a KernelDef,
    resource_i: usize,
    scalar_i: usize,
}

impl<'a> SchemeNodeStart<'a> {
    #[allow(private_bounds)]
    pub fn bind_resource(mut self, bindable: &impl SchemeBindable, access: NodeAccess) -> Self {
        let expected = self
            .def
            .params
            .iter()
            .filter(|p| p.category.is_resource())
            .nth(self.resource_i);
        if let Some(p) = expected {
            if let Some(want) = p.access {
                let want_na = access_kind_to_node(want);
                debug_assert_eq!(want_na, access, "kernel param `{}` expected {:?} access", p.name, want);
                let _ = want_na;
            }
        }
        self.resource_i += 1;
        self.builder = self.builder.with_parcel(bindable, access);
        self
    }

    pub fn bind_u32(mut self, value: u32) -> Self {
        self.scalar_i += 1;
        self.builder = self.builder.with_param(value);
        self
    }

    pub fn bind_i32(self, value: i32) -> Self {
        self.bind_u32(value as u32)
    }

    pub fn bind_f32(self, value: f32) -> Self {
        self.bind_u32(value.to_bits())
    }

    pub fn bind_bool(self, value: bool) -> Self {
        self.bind_u32(u32::from(value))
    }

    pub fn finish(self) -> DispatchBuilder<'a> {
        DispatchBuilder::new(self.builder, self.workgroup_size)
    }
}

fn access_kind_to_node(access: goldy_shader_ir::AccessKind) -> NodeAccess {
    match access {
        goldy_shader_ir::AccessKind::Read => NodeAccess::Read,
        goldy_shader_ir::AccessKind::Write => NodeAccess::Write,
        goldy_shader_ir::AccessKind::ReadWrite => NodeAccess::ReadWrite,
    }
}

/// Compile / cache a kernel definition into a [`PreparedKernel`].
///
/// Pipeline creation happens here (not on every `record`), matching the
/// existing `ShaderModule` + `ComputePipeline` path and disk cache.
pub fn prepare_kernel(device: &Device, def: KernelDef) -> Result<PreparedKernel> {
    if def.abi_version != goldy_shader_ir::KERNEL_ABI_VERSION {
        anyhow::bail!(
            "kernel ABI version mismatch: shader has {}, runtime expects {}",
            def.abi_version,
            goldy_shader_ir::KERNEL_ABI_VERSION
        );
    }

    dump_kernel_artifacts(&def, None)?;

    let shader = ShaderModule::from_slang(device, &def.source.canonical_slang)
        .with_context(|| format!("compiling rust kernel `{}`", def.entry))?;
    let pipeline = ComputePipeline::new_with_label(device, &shader, Some(&format!("rust_kernel_{}", def.entry)))?;

    Ok(PreparedKernel {
        pipeline: Arc::new(pipeline),
        def,
    })
}

/// Dump canonical Slang + ABI metadata when `GOLDY_DUMP_RUST_KERNELS` is set.
///
/// The variable may be `1`/`true` (dumps under the temp dir) or a directory path.
pub fn dump_kernel_artifacts(def: &KernelDef, override_dir: Option<&std::path::Path>) -> Result<()> {
    let dir = if let Some(d) = override_dir {
        Some(d.to_path_buf())
    } else {
        match std::env::var("GOLDY_DUMP_RUST_KERNELS") {
            Ok(v) if v == "1" || v.eq_ignore_ascii_case("true") || v.eq_ignore_ascii_case("yes") => {
                Some(std::env::temp_dir().join("goldy_rust_kernels"))
            }
            Ok(v) if !v.is_empty() => Some(PathBuf::from(v)),
            _ => None,
        }
    };
    let Some(dir) = dir else {
        return Ok(());
    };
    fs::create_dir_all(&dir)?;
    let stem = format!(
        "{}_{}x{}x{}",
        def.entry, def.workgroup_size[0], def.workgroup_size[1], def.workgroup_size[2]
    );
    fs::write(dir.join(format!("{stem}.slang")), &def.source.canonical_slang)?;
    let abi = format!(
        "abi_version = {}\nentry = {}\nworkgroup_size = {:?}\nparams = {:#?}\nbuiltins = {:?}\nsource = {}:{}\n",
        def.abi_version,
        def.entry,
        def.workgroup_size,
        def.params,
        def.builtins,
        def.source_map.rust_file,
        def.source_map.rust_line
    );
    fs::write(dir.join(format!("{stem}.abi.txt")), abi)?;
    Ok(())
}
