//! Prepare a [`KernelDef`] into a device-scoped compute pipeline.

use crate::compute::ComputePipeline;
use crate::kernel::{DispatchBuilder, KernelDef};
use crate::runtime::Runtime;
use crate::scheme::{Scheme, SchemeBindable};
use crate::shader::{KernelIdentity, ShaderModule};
use crate::task_graph::NodeAccess;
use anyhow::{Context, Result};
#[cfg(feature = "tensor")]
use goldy_shader_ir::{BoundTensorDim, TensorShapeSpec};
#[cfg(feature = "tensor")]
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use std::sync::Arc;

/// Symbolic extents unified across one generated `record` call.
#[derive(Debug, Default)]
pub struct TensorShapeEnv {
    #[cfg(feature = "tensor")]
    dims: HashMap<String, BoundTensorDim>,
}

impl TensorShapeEnv {
    pub fn new() -> Self {
        Self::default()
    }
}

/// Runtime-scoped prepared kernel: compiled pipeline + ABI metadata.
pub struct PreparedKernel {
    pipeline: Arc<ComputePipeline>,
    def: Arc<KernelDef>,
}

impl PreparedKernel {
    pub fn pipeline(&self) -> &ComputePipeline {
        &self.pipeline
    }

    /// Shared pipeline handle. Prefer this over copying [`ComputePipeline`] so Drop
    /// stays refcounted.
    pub fn pipeline_arc(&self) -> Arc<ComputePipeline> {
        Arc::clone(&self.pipeline)
    }

    pub fn def(&self) -> &KernelDef {
        &self.def
    }

    pub fn workgroup_size(&self) -> [u32; 3] {
        self.def.workgroup_size
    }

    /// Begin a Scheme node for this kernel (untyped escape hatch).
    ///
    /// Prefer the typed `record` method generated by `#[goldy::compute]`.
    pub fn begin_record<'a>(
        &'a self,
        scheme: &'a mut Scheme,
        label: impl Into<crate::SchemeLabel>,
    ) -> SchemeNodeStart<'a> {
        let mut builder = scheme.node(label, self.pipeline.as_ref());
        if crate::fusion_plan::fusable_kernel(&self.def) {
            builder.begin_kernel_site(Arc::clone(&self.def));
        }
        SchemeNodeStart {
            builder,
            workgroup_size: self.def.workgroup_size,
            def: &self.def,
            resource_i: 0,
            scalar_i: 0,
            last_scalar: 0,
            facts: Vec::new(),
            #[cfg(feature = "tensor")]
            tensor_layouts: Vec::new(),
        }
    }
}

/// Helper used by generated `record` methods to bind ABI-ordered arguments.
pub struct SchemeNodeStart<'a> {
    builder: crate::scheme::SchemeNodeBuilder<'a>,
    workgroup_size: [u32; 3],
    def: &'a KernelDef,
    resource_i: usize,
    scalar_i: usize,
    last_scalar: u32,
    /// Scalars marked `#[fact]`, as `(slot, word)`.
    facts: crate::specialization::BakedSlots,
    #[cfg(feature = "tensor")]
    tensor_layouts: Vec<crate::tensor::GoldyTensorLayout>,
}

impl<'a> SchemeNodeStart<'a> {
    #[allow(private_bounds)]
    pub fn bind_resource(mut self, bindable: &impl SchemeBindable, access: NodeAccess) -> Self {
        self.note_resource_access(access);
        self.builder = self.builder.with_parcel(bindable, access);
        self
    }

    pub fn bind_temporary(mut self, temporary: &crate::Temporary, access: NodeAccess) -> Self {
        self.note_resource_access(access);
        self.builder = self.builder.with_temporary(temporary, access);
        self
    }

    #[cfg(feature = "graphics")]
    pub fn bind_present(mut self, lease: &crate::PresentLease, access: NodeAccess) -> Self {
        self.note_resource_access(access);
        self.builder = self.builder.with_present_access(lease, access);
        self
    }

    fn note_resource_access(&mut self, access: NodeAccess) {
        let expected = self
            .def
            .params
            .iter()
            .filter(|p| p.category.is_resource())
            .nth(self.resource_i);
        if let Some(p) = expected {
            if let Some(want) = p.access {
                let want_na = access_kind_to_node(want);
                debug_assert_eq!(want_na, access, "kernel param `{}` expected {:?} access", p.name, want);
                let _ = want_na;
            }
        }
        self.resource_i += 1;
    }

    pub fn bind_u32(mut self, value: u32) -> Self {
        self.scalar_i += 1;
        self.last_scalar = value;
        self.builder = self.builder.with_param(value);
        self
    }

    /// Declare the scalar bound last fixed for the node's lifetime (`#[fact]`).
    ///
    /// The specialization predictor bakes it at the node's first submit instead of
    /// waiting for it to hold still. Changing it later with `Scheme::set_node_param`
    /// is still correct; the node then treats it as an ordinary param.
    pub fn mark_fact(mut self) -> Self {
        debug_assert!(self.scalar_i > 0, "mark_fact follows a scalar bind");
        self.facts.push((self.scalar_i as u32 - 1, self.last_scalar));
        self
    }

    pub fn bind_i32(self, value: i32) -> Self {
        self.bind_u32(value as u32)
    }

    pub fn bind_f32(self, value: f32) -> Self {
        self.bind_u32(value.to_bits())
    }

    pub fn bind_bool(self, value: bool) -> Self {
        self.bind_u32(u32::from(value))
    }

    /// Validate dtype, writeability, and the parameter's shape contract without binding.
    ///
    /// Generated `record` methods call this for every tensor argument before any
    /// parcel bind or GraphIR growth.
    #[cfg(feature = "tensor")]
    pub fn check_tensor_view(
        &self,
        view: crate::tensor::TensorView<'_>,
        param_name: &str,
        access: NodeAccess,
        expected_dtype: crate::tensor::TensorDType,
        env: &mut TensorShapeEnv,
    ) -> Result<(), crate::error::GoldyError> {
        view.layout().require_dtype(expected_dtype, "kernel tensor")?;
        if matches!(access, NodeAccess::Write | NodeAccess::ReadWrite) {
            view.layout().require_writeable("kernel tensor")?;
        }
        let Some(param) = self.def.params.iter().find(|p| p.name == param_name) else {
            return Err(crate::error::GoldyError::Validation(format!(
                "kernel `{}` has no parameter `{param_name}`",
                self.def.entry
            )));
        };
        if let Some(spec) = &param.shape_spec {
            check_tensor_shape_spec(&self.def.entry, param_name, spec, view.shape().dims(), env)?;
        }
        Ok(())
    }

    /// Bind a tensor view as the next resource: parent parcel + collected layout metadata.
    #[cfg(feature = "tensor")]
    pub fn bind_tensor_view(
        mut self,
        view: crate::tensor::TensorView<'_>,
        access: NodeAccess,
        expected_dtype: crate::tensor::TensorDType,
    ) -> Result<Self, crate::error::GoldyError> {
        view.layout().require_dtype(expected_dtype, "kernel tensor")?;
        if matches!(access, NodeAccess::Write | NodeAccess::ReadWrite) {
            view.layout().require_writeable("kernel tensor")?;
        }
        let coords = view.layout().gpu_coords()?;
        self.tensor_layouts.push(coords);
        Ok(self.bind_resource(&view, access))
    }

    /// Pack collected tensor layouts into a scheme-owned metadata parcel and bind it last.
    ///
    /// The first [`goldy_shader_ir::TENSOR_LAUNCH_WORDS`] element offsets also travel as
    /// launch words, and every tensor's shape facts go to the specialization predictor as
    /// certain facts; the parcel serves the universal program and tensors past the launch
    /// words.
    #[cfg(feature = "tensor")]
    pub fn finish_with_tensor_meta(mut self) -> Result<DispatchBuilder<'a>, crate::error::GoldyError> {
        let layouts = std::mem::take(&mut self.tensor_layouts);
        if layouts.is_empty() {
            return Err(crate::error::GoldyError::Validation(
                "kernel tensor metadata: no tensor views were bound".into(),
            ));
        }
        let offsets = layouts
            .iter()
            .take(goldy_shader_ir::TENSOR_LAUNCH_WORDS)
            .map(|l| l.offset)
            .collect();
        self.facts.extend(layouts.iter().enumerate().flat_map(|(slot, l)| {
            tensor_fact_words(l)
                .into_iter()
                .enumerate()
                .map(move |(fact, word)| (crate::specialization::tensor_fact_slot(slot as u32, fact), word))
        }));
        let runtime = self.builder.scheme_runtime();
        let buf = runtime
            .acquire_buffer_with_data(&layouts, crate::types::BufferKind::Scattered)
            .map_err(crate::error::GoldyError::from)?;
        self.builder = self
            .builder
            .with_launch_words(offsets)
            .bind_record_constant(buf, NodeAccess::Read);
        Ok(self.finish())
    }

    pub fn finish(self) -> DispatchBuilder<'a> {
        let builder = self.builder.with_certain_facts(self.facts);
        DispatchBuilder::new(builder, self.workgroup_size)
    }
}

/// `layout`'s fields in [`goldy_shader_ir::TENSOR_FACTS`] order.
#[cfg(feature = "tensor")]
fn tensor_fact_words(layout: &crate::tensor::GoldyTensorLayout) -> [u32; goldy_shader_ir::TENSOR_FACTS.len()] {
    let [d0, d1, d2, d3] = layout.shape;
    let [s0, s1, s2, s3] = layout.stride;
    [layout.rank, layout.numel, d0, d1, d2, d3, s0, s1, s2, s3, layout.flags]
}

pub(crate) fn access_kind_to_node(access: goldy_shader_ir::AccessKind) -> NodeAccess {
    match access {
        goldy_shader_ir::AccessKind::Read => NodeAccess::Read,
        goldy_shader_ir::AccessKind::Write => NodeAccess::Write,
        goldy_shader_ir::AccessKind::ReadWrite => NodeAccess::ReadWrite,
    }
}

/// Compile / cache a kernel definition into a [`PreparedKernel`].
///
/// Pipeline creation happens here (not on every `record`), matching the
/// existing `ShaderModule` + `ComputePipeline` path and disk cache.
pub fn prepare_kernel(device: &Runtime, def: KernelDef) -> Result<PreparedKernel> {
    prepare_kernel_as(device, def, None)
}

/// [`prepare_kernel`] for a program whose variants are shared by every module of `identity`.
pub(super) fn prepare_kernel_as(
    device: &Runtime,
    def: KernelDef,
    identity: Option<KernelIdentity>,
) -> Result<PreparedKernel> {
    if def.abi_version != goldy_shader_ir::KERNEL_ABI_VERSION {
        anyhow::bail!(
            "kernel ABI version mismatch: shader has {}, runtime expects {}",
            def.abi_version,
            goldy_shader_ir::KERNEL_ABI_VERSION
        );
    }

    if let Some(definition) = &def.definition {
        debug_assert_eq!(
            goldy_shader_ir::emit_canonical_compute_source(definition)
                .source
                .canonical_slang,
            def.source.canonical_slang,
            "kernel `{}`: retained definition does not lower to its canonical source",
            definition.name
        );
    }
    dump_kernel_artifacts(&def, None)?;

    let mut shader = ShaderModule::from_slang(device, &def.source.canonical_slang)
        .with_context(|| format!("compiling rust kernel `{}`", def.entry))?;
    if let Some(identity) = identity {
        shader = shader.with_kernel_identity(identity);
    }
    let pipeline = ComputePipeline::new_with_label(device, &shader, Some(&format!("rust_kernel_{}", def.entry)))?;

    Ok(PreparedKernel {
        pipeline: Arc::new(pipeline),
        def: Arc::new(def),
    })
}

/// Dump canonical Slang + ABI metadata when `GOLDY_DUMP_RUST_KERNELS` is set.
///
/// The variable may be `1`/`true` (dumps under the temp dir) or a directory path.
pub fn dump_kernel_artifacts(def: &KernelDef, override_dir: Option<&std::path::Path>) -> Result<()> {
    let dir = if let Some(d) = override_dir {
        Some(d.to_path_buf())
    } else {
        match std::env::var("GOLDY_DUMP_RUST_KERNELS") {
            Ok(v) if v == "1" || v.eq_ignore_ascii_case("true") || v.eq_ignore_ascii_case("yes") => {
                Some(std::env::temp_dir().join("goldy_rust_kernels"))
            }
            Ok(v) if !v.is_empty() => Some(PathBuf::from(v)),
            _ => None,
        }
    };
    let Some(dir) = dir else {
        return Ok(());
    };
    fs::create_dir_all(&dir)?;
    let stem = format!(
        "{}_{}x{}x{}",
        def.entry, def.workgroup_size[0], def.workgroup_size[1], def.workgroup_size[2]
    );
    fs::write(dir.join(format!("{stem}.slang")), &def.source.canonical_slang)?;
    let abi = format!(
        "abi_version = {}\nentry = {}\nworkgroup_size = {:?}\nparams = {:#?}\nshape_contracts = {}\nbuiltins = {:?}\nsource = {}:{}\n",
        def.abi_version,
        def.entry,
        def.workgroup_size,
        def.params,
        format_shape_contracts(&def.params),
        def.builtins,
        def.source_map.rust_file,
        def.source_map.rust_line
    );
    fs::write(dir.join(format!("{stem}.abi.txt")), abi)?;
    Ok(())
}

#[cfg(feature = "tensor")]
fn check_tensor_shape_spec(
    kernel: &str,
    param: &str,
    spec: &TensorShapeSpec,
    actual: &[u32],
    env: &mut TensorShapeEnv,
) -> Result<(), crate::error::GoldyError> {
    spec.check(kernel, param, actual, &mut env.dims)
        .map_err(crate::error::GoldyError::Validation)
}

fn format_shape_contracts(params: &[goldy_shader_ir::KernelParam]) -> String {
    let mut parts = Vec::new();
    for p in params {
        if !p.is_tensor {
            continue;
        }
        match &p.shape_spec {
            Some(spec) => parts.push(format!("{}: {}", p.name, spec)),
            None => parts.push(format!("{}: <any>", p.name)),
        }
    }
    if parts.is_empty() {
        "<none>".into()
    } else {
        parts.join(", ")
    }
}
