/*
 * Goldy GPU Library - C API Header
 * 
 * Auto-generated by cbindgen. Do not edit manually.
 * 
 * MIT License - Copyright (c) 2025-2026 Mohamed Koubaa
 * 
 * This header provides the C API for the Goldy GPU library.
 * For C++ RAII wrappers, include goldy.hpp instead.
 */


#ifndef GOLDY_H
#define GOLDY_H

/* Generated with cbindgen:0.29.4 */

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Result codes for FFI functions.
typedef enum GoldyResult {
    // Operation succeeded.
    GOLDY_RESULT_OK = 0,
    // Invalid argument provided.
    GOLDY_RESULT_INVALID_ARGUMENT = 1,
    // Null pointer provided.
    GOLDY_RESULT_NULL_POINTER = 2,
    // GPU operation failed.
    GOLDY_RESULT_GPU_ERROR = 3,
    // Shader compilation failed.
    GOLDY_RESULT_SHADER_ERROR = 4,
    // Resource creation failed.
    GOLDY_RESULT_RESOURCE_ERROR = 5,
    // Internal error.
    GOLDY_RESULT_INTERNAL_ERROR = 6,
} GoldyResult;

// Graphics backend type.
typedef enum GoldyBackendType {
    GOLDY_BACKEND_TYPE_VULKAN = 0,
    GOLDY_BACKEND_TYPE_METAL = 1,
    GOLDY_BACKEND_TYPE_DX12 = 2,
} GoldyBackendType;

// GPU device type.
typedef enum GoldyDeviceType {
    GOLDY_DEVICE_TYPE_DISCRETE_GPU = 0,
    GOLDY_DEVICE_TYPE_INTEGRATED_GPU = 1,
    GOLDY_DEVICE_TYPE_CPU = 2,
    GOLDY_DEVICE_TYPE_OTHER = 3,
} GoldyDeviceType;

// Vertex format.
typedef enum GoldyVertexFormat {
    GOLDY_VERTEX_FORMAT_FLOAT32 = 0,
    GOLDY_VERTEX_FORMAT_FLOAT32X2 = 1,
    GOLDY_VERTEX_FORMAT_FLOAT32X3 = 2,
    GOLDY_VERTEX_FORMAT_FLOAT32X4 = 3,
    GOLDY_VERTEX_FORMAT_UINT32 = 4,
    GOLDY_VERTEX_FORMAT_SINT32 = 5,
    GOLDY_VERTEX_FORMAT_UINT8X4 = 6,
    GOLDY_VERTEX_FORMAT_UNORM8X4 = 7,
} GoldyVertexFormat;

// Primitive topology.
typedef enum GoldyPrimitiveTopology {
    GOLDY_PRIMITIVE_TOPOLOGY_POINT_LIST = 0,
    GOLDY_PRIMITIVE_TOPOLOGY_LINE_LIST = 1,
    GOLDY_PRIMITIVE_TOPOLOGY_LINE_STRIP = 2,
    GOLDY_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST = 3,
    GOLDY_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP = 4,
} GoldyPrimitiveTopology;

// Texture format.
typedef enum GoldyTextureFormat {
    GOLDY_TEXTURE_FORMAT_RGBA8_UNORM_SRGB = 0,
    GOLDY_TEXTURE_FORMAT_RGBA8_UNORM = 1,
    GOLDY_TEXTURE_FORMAT_BGRA8_UNORM_SRGB = 2,
    GOLDY_TEXTURE_FORMAT_BGRA8_UNORM = 3,
    GOLDY_TEXTURE_FORMAT_RGBA16_FLOAT = 4,
    GOLDY_TEXTURE_FORMAT_RGBA32_FLOAT = 5,
    GOLDY_TEXTURE_FORMAT_R8_UNORM = 6,
    GOLDY_TEXTURE_FORMAT_RG8_UNORM = 7,
} GoldyTextureFormat;

// Depth format.
typedef enum GoldyDepthFormat {
    GOLDY_DEPTH_FORMAT_DEPTH16_UNORM = 0,
    GOLDY_DEPTH_FORMAT_DEPTH24_PLUS = 1,
    GOLDY_DEPTH_FORMAT_DEPTH24_PLUS_STENCIL8 = 2,
    GOLDY_DEPTH_FORMAT_DEPTH32_FLOAT = 3,
    GOLDY_DEPTH_FORMAT_DEPTH32_FLOAT_STENCIL8 = 4,
} GoldyDepthFormat;

// Comparison function for depth testing.
typedef enum GoldyCompareFunction {
    GOLDY_COMPARE_FUNCTION_NEVER = 0,
    GOLDY_COMPARE_FUNCTION_LESS = 1,
    GOLDY_COMPARE_FUNCTION_EQUAL = 2,
    GOLDY_COMPARE_FUNCTION_LESS_EQUAL = 3,
    GOLDY_COMPARE_FUNCTION_GREATER = 4,
    GOLDY_COMPARE_FUNCTION_NOT_EQUAL = 5,
    GOLDY_COMPARE_FUNCTION_GREATER_EQUAL = 6,
    GOLDY_COMPARE_FUNCTION_ALWAYS = 7,
} GoldyCompareFunction;

// Data access pattern for buffers.
//
// - `Scattered`: Any thread, any address, read/write. No coherence assumptions.
// - `Broadcast`: All threads read same address. Hardware broadcast optimization.
typedef enum GoldyBufferKind {
    // Any thread, any address, read/write (StructuredBuffer, RWStructuredBuffer).
    GOLDY_BUFFER_KIND_SCATTERED = 0,
    // All threads same address, broadcast optimized (ConstantBuffer).
    GOLDY_BUFFER_KIND_BROADCAST = 1,
} GoldyBufferKind;

// Spatial access pattern for textures.
//
// - `Interpolated`: Hardware filtering between neighbors (texture units).
// - `Direct`: Direct 2D/3D indexing, no filtering, read/write.
// - `DirectInterpolated`: Both storage (UAV) and sampled (SRV) access on the same texture.
typedef enum GoldyTextureKind {
    // Hardware filtering between neighbors (Texture2D with sampler).
    GOLDY_TEXTURE_KIND_INTERPOLATED = 0,
    // Direct 2D/3D indexing, no filtering (RWTexture2D).
    GOLDY_TEXTURE_KIND_DIRECT = 1,
    // Both UAV (storage/write) and SRV (sampled/read) access on the same texture.
    GOLDY_TEXTURE_KIND_DIRECT_INTERPOLATED = 2,
} GoldyTextureKind;

// Texture addressing mode.
typedef enum GoldyAddressMode {
    GOLDY_ADDRESS_MODE_CLAMP_TO_EDGE = 0,
    GOLDY_ADDRESS_MODE_REPEAT = 1,
    GOLDY_ADDRESS_MODE_MIRROR_REPEAT = 2,
} GoldyAddressMode;

// Texture filter mode.
typedef enum GoldyFilterMode {
    GOLDY_FILTER_MODE_NEAREST = 0,
    GOLDY_FILTER_MODE_LINEAR = 1,
} GoldyFilterMode;

// Per-node resource access for task graph bindings.
typedef enum GoldyNodeAccess {
    GOLDY_NODE_ACCESS_READ = 0,
    GOLDY_NODE_ACCESS_WRITE = 1,
    GOLDY_NODE_ACCESS_READ_WRITE = 2,
    GOLDY_NODE_ACCESS_OVERWRITE = 3,
} GoldyNodeAccess;

// Color-target load declared on [`goldy_scheme_render_pass_begin`].
typedef enum GoldyTargetLoad {
    GOLDY_TARGET_LOAD_LOAD = 0,
    GOLDY_TARGET_LOAD_CLEAR = 1,
    GOLDY_TARGET_LOAD_DISCARD = 2,
} GoldyTargetLoad;

// Index format.
typedef enum GoldyIndexFormat {
    GOLDY_INDEX_FORMAT_UINT16 = 0,
    GOLDY_INDEX_FORMAT_UINT32 = 1,
} GoldyIndexFormat;

// Opaque handle to an acquired [`goldy::Buffer`].
typedef struct GoldyBuffer GoldyBuffer;

// One submission's claim extracted from a transaction.
typedef struct GoldyClaim GoldyClaim;

// Opaque handle to a Goldy ComputePipeline.
typedef struct GoldyComputePipeline GoldyComputePipeline;

// Opaque handle to a Goldy submission context.
typedef struct GoldyContext GoldyContext;

// Opaque handle to a Goldy Device.
typedef struct GoldyDevice GoldyDevice;

// Opaque handle to a Goldy Instance.
typedef struct GoldyInstance GoldyInstance;

// Opaque handle to a bindable [`goldy::Parcel`] (buffer units; textures use [`GoldyTexture`]).
typedef struct GoldyParcel GoldyParcel;

// Opaque handle to a stable present lease from a surface exchange.
typedef struct GoldyPresentLease GoldyPresentLease;

// Opaque read-easement grant handle returned by [`goldy_scheme_grant_read`].
//
// Heap-allocated; destroy with [`goldy_read_grant_destroy`].
typedef struct GoldyReadGrant GoldyReadGrant;

// Builder for a retained record buffer (one backing buffer, multiple sub-views).
typedef struct GoldyRecordBuilder GoldyRecordBuilder;

// Opaque handle to a Goldy RenderPipeline.
typedef struct GoldyRenderPipeline GoldyRenderPipeline;

// Opaque handle to a Goldy retained allocation pool.
typedef struct GoldyRetainedPool GoldyRetainedPool;

// Opaque handle to a Goldy Sampler.
typedef struct GoldySampler GoldySampler;

// Opaque handle to a retained Goldy scheme.
typedef struct GoldyScheme GoldyScheme;

// Opaque handle to a scheme-held render-target lease.
typedef struct GoldySchemeRenderTargetLease GoldySchemeRenderTargetLease;

// Opaque per-submission token returned by [`goldy_scheme_submit`].
//
// Heap-allocated; destroy with [`goldy_scheme_submission_destroy`].
typedef struct GoldySchemeSubmission GoldySchemeSubmission;

// Opaque handle to a Goldy ShaderModule.
typedef struct GoldyShaderModule GoldyShaderModule;

// Opaque handle to a window-surface exchange.
typedef struct GoldySurfaceExchange GoldySurfaceExchange;

// Opaque handle to an acquired [`goldy::Texture`].
typedef struct GoldyTexture GoldyTexture;

// Erased exchange transaction recorded in a scheme.
typedef struct GoldyTransaction GoldyTransaction;

// Adapter info.
typedef struct GoldyAdapterInfo {
    uint32_t id;
    enum GoldyDeviceType device_type;
    char name[256];
    char vendor[64];
} GoldyAdapterInfo;

// Vertex attribute description.
typedef struct GoldyVertexAttribute {
    uint32_t location;
    enum GoldyVertexFormat format;
    uint32_t offset;
} GoldyVertexAttribute;

// Render pipeline descriptor for FFI.
typedef struct GoldyRenderPipelineDesc {
    // Pointer to vertex attributes array.
    const struct GoldyVertexAttribute *vertex_attributes;
    // Number of vertex attributes.
    uint32_t vertex_attribute_count;
    // Stride in bytes between vertices.
    uint32_t vertex_stride;
    // Primitive topology.
    enum GoldyPrimitiveTopology topology;
    // Target texture format.
    enum GoldyTextureFormat target_format;
    // Whether depth testing is enabled.
    bool depth_enabled;
    // Depth format (only used if depth_enabled is true).
    enum GoldyDepthFormat depth_format;
    // Whether to write depth values.
    bool depth_write_enabled;
    // Depth comparison function.
    enum GoldyCompareFunction depth_compare;
} GoldyRenderPipelineDesc;

// Texture flags for copy and render operations.
typedef struct GoldyTextureFlags {
    uint32_t _0;
} GoldyTextureFlags;
#define GoldyTextureFlags_NONE (GoldyTextureFlags){ ._0 = 0 }
#define GoldyTextureFlags_COPY_SRC (GoldyTextureFlags){ ._0 = (1 << 0) }
#define GoldyTextureFlags_COPY_DST (GoldyTextureFlags){ ._0 = (1 << 1) }
#define GoldyTextureFlags_RENDER_TARGET (GoldyTextureFlags){ ._0 = (1 << 2) }

// Sampler descriptor.
typedef struct GoldySamplerDesc {
    enum GoldyAddressMode address_mode_u;
    enum GoldyAddressMode address_mode_v;
    enum GoldyAddressMode address_mode_w;
    enum GoldyFilterMode mag_filter;
    enum GoldyFilterMode min_filter;
    enum GoldyFilterMode mipmap_filter;
    float max_anisotropy;
    float lod_min_clamp;
    float lod_max_clamp;
} GoldySamplerDesc;

// RGBA color with floating point components (0.0 - 1.0).
typedef struct GoldyColor {
    float r;
    float g;
    float b;
    float a;
} GoldyColor;

// Outcome counters for [`goldy_scheme_replay_stats`].
typedef struct GoldyReplayStats {
    uint64_t records;
    uint64_t resubmit_hits;
} GoldyReplayStats;

// Out-parameters for [`goldy_surface_exchange_bind_destination`].
typedef struct GoldySurfaceExchangeBindDestinationOut {
    struct GoldyPresentLease *lease;
    struct GoldyTransaction *transaction;
} GoldySurfaceExchangeBindDestinationOut;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint64_t goldy_buffer_byte_size(const struct GoldyBuffer *buffer);

void goldy_buffer_destroy(struct GoldyBuffer *buffer);

// Borrow one bindable unit from a retained buffer as an owned [`GoldyParcel`] handle.
//
// The returned parcel shares dependency-tracking state with the buffer unit.
// Destroy with [`goldy_parcel_destroy`]. The source buffer must remain alive
// for the duration of GPU use.
struct GoldyParcel *goldy_buffer_field(const struct GoldyBuffer *buffer, uint32_t unit);

uint64_t goldy_buffer_unit_byte_size(const struct GoldyBuffer *buffer, uint32_t unit);

uint32_t goldy_buffer_unit_count(const struct GoldyBuffer *buffer);

enum GoldyResult goldy_buffer_unit_read_to_cpu(const struct GoldyBuffer *buffer,
                                               uint32_t unit,
                                               const struct GoldyDevice *device,
                                               uint8_t *output,
                                               size_t output_size);

// Perform the claim's external handoff (for example present).
//
// # Safety
// `claim` must be valid.
enum GoldyResult goldy_claim_consume(struct GoldyClaim *claim);

// Destroy a claim without consuming or discarding intentionally.
//
// # Safety
// `claim` must be valid and not used after this call.
void goldy_claim_destroy(struct GoldyClaim *claim);

// Settle the claim without intentionally performing the external operation.
//
// # Safety
// `claim` must be valid.
enum GoldyResult goldy_claim_discard(struct GoldyClaim *claim);

// Clear the last error message.
void goldy_clear_error(void);

// Create a new compute pipeline.
//
// Returns a pointer to the pipeline, or null on failure.
//
// # Safety
// All pointers must be valid.
struct GoldyComputePipeline *goldy_compute_pipeline_create(const struct GoldyDevice *device,
                                                           const struct GoldyShaderModule *compute_shader);

// Destroy a compute pipeline.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_compute_pipeline_destroy(struct GoldyComputePipeline *pipeline);

// Create a context bound to `device`.
//
// A context is the submission lifetime anchor for retained [`crate::scheme::GoldyScheme`]
// instances on the same device.
//
// # Safety
// `device` must be valid.
struct GoldyContext *goldy_context_create(const struct GoldyDevice *device);

// Destroy a context.
//
// # Safety
// `ctx` must be valid and not used after this call.
void goldy_context_destroy(struct GoldyContext *ctx);

// Smoke-test helper: returns [`GoldyResult::Ok`] when `ctx` is non-null.
//
// # Safety
// `ctx` must be valid when non-null.
enum GoldyResult goldy_context_is_valid(const struct GoldyContext *ctx);

// Get the adapter ID this device was created on.
//
// # Safety
// The device pointer must be valid.
uint32_t goldy_device_adapter_id(const struct GoldyDevice *device);

// Destroy a device.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_device_destroy(struct GoldyDevice *device);

// Check if a shader library is registered.
//
// # Safety
// The device pointer and name must be valid.
bool goldy_device_has_library(const struct GoldyDevice *device, const char *name);

// Check if the device is still valid.
//
// # Safety
// The device pointer must be valid.
bool goldy_device_is_valid(const struct GoldyDevice *device);

// Get the last error message.
//
// Returns a pointer to a null-terminated string. The pointer is valid until
// the next FFI call on the same thread.
//
// Returns null if no error has occurred.
const char *goldy_get_last_error(void);

// Get the number of available adapters.
//
// # Safety
// The instance pointer must be valid.
uint32_t goldy_instance_adapter_count(const struct GoldyInstance *instance);

// Get the backend type of an instance.
//
// # Safety
// The instance pointer must be valid.
enum GoldyBackendType goldy_instance_backend_type(const struct GoldyInstance *instance);

// Create a new Goldy instance.
//
// Returns a pointer to the instance, or null on failure.
// Call `goldy_get_last_error()` to get the error message.
struct GoldyInstance *goldy_instance_create(void);

// Create a device for a specific adapter ID.
//
// Returns a pointer to the device, or null on failure.
//
// # Safety
// The instance pointer must be valid.
struct GoldyDevice *goldy_instance_create_device_for_adapter(const struct GoldyInstance *instance,
                                                             uint32_t adapter_id);

// Destroy an instance.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_instance_destroy(struct GoldyInstance *instance);

// Get adapter info at the given index.
//
// # Safety
// The instance pointer must be valid.
// The info pointer must point to a valid GoldyAdapterInfo struct.
enum GoldyResult goldy_instance_get_adapter(const struct GoldyInstance *instance,
                                            uint32_t index,
                                            struct GoldyAdapterInfo *info);

uint64_t goldy_parcel_byte_size(const struct GoldyParcel *parcel);

void goldy_parcel_destroy(struct GoldyParcel *parcel);

// Destroy a present lease handle.
//
// # Safety
// `lease` must be valid and not used after this call.
void goldy_present_lease_destroy(struct GoldyPresentLease *lease);

// Logical byte size of readable data for this grant.
//
// # Safety
// `grant` must be valid.
uint64_t goldy_read_grant_byte_size(const struct GoldyReadGrant *grant);

// Consume bytes for the `(grant × submission)` cell into `output`.
//
// Blocks until this submission's GPU work (dispatch + grant staging copy) completes.
// Each submission may be consumed at most once per grant. Drop the submission when done if you
// rely on staging-buffer reuse.
//
// # Safety
// All pointers must be valid. `output` must point to at least `output_size` bytes.
enum GoldyResult goldy_read_grant_consume(const struct GoldyReadGrant *grant,
                                          const struct GoldySchemeSubmission *submission,
                                          uint8_t *output,
                                          size_t output_size);

// Destroy a read grant from [`goldy_scheme_grant_read`].
//
// # Safety
// `grant` must be valid and not used after this call.
void goldy_read_grant_destroy(struct GoldyReadGrant *grant);

struct GoldyBuffer *goldy_record_builder_build(struct GoldyRecordBuilder *builder,
                                               struct GoldyRetainedPool *pool);

struct GoldyRecordBuilder *goldy_record_builder_create(void);

void goldy_record_builder_destroy(struct GoldyRecordBuilder *builder);

uint32_t goldy_record_builder_emplace(struct GoldyRecordBuilder *builder,
                                      const char *name,
                                      const uint8_t *data,
                                      size_t data_size,
                                      uint64_t element_count,
                                      uint32_t element_stride);

uint32_t goldy_record_builder_reserve(struct GoldyRecordBuilder *builder,
                                      const char *name,
                                      uint64_t element_count,
                                      uint32_t element_stride);

// Create a new render pipeline.
//
// Returns a pointer to the pipeline, or null on failure.
//
// # Safety
// All pointers must be valid.
struct GoldyRenderPipeline *goldy_render_pipeline_create(const struct GoldyDevice *device,
                                                         const struct GoldyShaderModule *vertex_shader,
                                                         const struct GoldyShaderModule *fragment_shader,
                                                         const struct GoldyRenderPipelineDesc *desc);

// Destroy a render pipeline.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_render_pipeline_destroy(struct GoldyRenderPipeline *pipeline);

struct GoldyBuffer *goldy_retained_pool_acquire_buffer(struct GoldyRetainedPool *pool,
                                                       uint64_t size,
                                                       enum GoldyBufferKind access,
                                                       uint32_t element_stride,
                                                       const uint8_t *data,
                                                       size_t data_size);

struct GoldyTexture *goldy_retained_pool_acquire_texture(struct GoldyRetainedPool *pool,
                                                         uint32_t width,
                                                         uint32_t height,
                                                         enum GoldyTextureFormat format,
                                                         enum GoldyTextureKind access,
                                                         struct GoldyTextureFlags flags,
                                                         const uint8_t *data,
                                                         size_t data_size);

struct GoldyRetainedPool *goldy_retained_pool_create(const struct GoldyDevice *device);

void goldy_retained_pool_destroy(struct GoldyRetainedPool *pool);

// Create a new sampler with the given descriptor.
//
// Returns a pointer to the sampler, or null on failure.
//
// # Safety
// All pointers must be valid.
struct GoldySampler *goldy_sampler_create(const struct GoldyDevice *device,
                                          const struct GoldySamplerDesc *desc);

// Create a sampler with default settings.
//
// Returns a pointer to the sampler, or null on failure.
//
// # Safety
// The device pointer must be valid.
struct GoldySampler *goldy_sampler_create_default(const struct GoldyDevice *device);

// Destroy a sampler.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_sampler_destroy(struct GoldySampler *sampler);

// Begin recording a compute dispatch node.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_scheme_compute_node_begin(struct GoldyScheme *scheme,
                                                 const char *label,
                                                 const struct GoldyComputePipeline *pipeline);

// Finalize the active compute node with a direct dispatch.
//
// # Safety
// `scheme` must be valid.
enum GoldyResult goldy_scheme_compute_node_dispatch(struct GoldyScheme *scheme,
                                                    uint32_t workgroups_x,
                                                    uint32_t workgroups_y,
                                                    uint32_t workgroups_z);

// Declare a buffer unit for the active compute node (shader binding + dependency).
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_scheme_compute_node_with_buffer_unit(struct GoldyScheme *scheme,
                                                            const struct GoldyBuffer *buffer,
                                                            uint32_t unit,
                                                            enum GoldyNodeAccess node_access);

// Bind one field of a partitioned retained buffer to the active compute node.
enum GoldyResult goldy_scheme_compute_node_with_field(struct GoldyScheme *scheme,
                                                      const struct GoldyBuffer *buffer,
                                                      uint32_t unit,
                                                      enum GoldyNodeAccess node_access);

// Append one scalar virtual-main parameter for the active compute node.
//
// # Safety
// `scheme` must be valid and a compute node must be active.
enum GoldyResult goldy_scheme_compute_node_with_param(struct GoldyScheme *scheme, uint32_t value);

// Declare a retained parcel for the active compute node.
//
// Registers both the graph dependency and the bindless shader slot internally —
// callers never pass resource indices.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_scheme_compute_node_with_parcel(struct GoldyScheme *scheme,
                                                       const struct GoldyParcel *parcel,
                                                       enum GoldyNodeAccess node_access);

// Declare a retained texture for the active compute node (shader binding + dependency).
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_scheme_compute_node_with_texture(struct GoldyScheme *scheme,
                                                        const struct GoldyTexture *texture,
                                                        enum GoldyNodeAccess node_access);

// Copy a scheme-held render target into a texture parcel (for grant readback).
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_scheme_copy_to_texture(struct GoldyScheme *scheme,
                                              const struct GoldySchemeRenderTargetLease *src_lease,
                                              const struct GoldyTexture *dst_texture);

// Create a scheme bound to `ctx`.
//
// # Safety
// `ctx` must be valid.
struct GoldyScheme *goldy_scheme_create(const struct GoldyContext *ctx);

// Destroy a scheme.
//
// # Safety
// `scheme` must be valid and not used after this call.
void goldy_scheme_destroy(struct GoldyScheme *scheme);

// Record a read-easement grant over a **buffer** parcel (once per scheme).
//
// For texture parcels use [`goldy_scheme_grant_read_texture`].
//
// Returns a heap-allocated [`GoldyReadGrant`]; destroy with [`goldy_read_grant_destroy`].
// Call after the producing dispatch node(s). Marks the scheme dirty.
//
// # Safety
// All pointers must be valid.
struct GoldyReadGrant *goldy_scheme_grant_read(struct GoldyScheme *scheme,
                                               const struct GoldyParcel *parcel);

//
// Like [`goldy_scheme_grant_read`] but requires a texture parcel with [`TextureFlags::COPY_SRC`].
//
// # Safety
// All pointers must be valid.
struct GoldyReadGrant *goldy_scheme_grant_read_texture(struct GoldyScheme *scheme,
                                                       const struct GoldyTexture *texture);

// True when the next submit must re-record.
//
// # Safety
// `scheme` must be valid.
bool goldy_scheme_is_dirty(const struct GoldyScheme *scheme);

// Declare a render-target lease on `scheme` (N=1 backing).
//
// Returns a heap-allocated lease handle; destroy with [`goldy_scheme_render_target_lease_destroy`].
// The lease is valid until the scheme is destroyed.
//
// # Safety
// `scheme` must be valid.
struct GoldySchemeRenderTargetLease *goldy_scheme_lease_render_target(struct GoldyScheme *scheme,
                                                                      uint32_t width,
                                                                      uint32_t height,
                                                                      enum GoldyTextureFormat format,
                                                                      bool has_depth,
                                                                      enum GoldyDepthFormat depth_format);

// Number of nodes recorded in the scheme IR.
//
// # Safety
// `scheme` must be valid.
uint32_t goldy_scheme_len(const struct GoldyScheme *scheme);

// Begin recording an offscreen render pass on a scheme-held lease.
//
// `clear_color` is used only when `load == GoldyTargetLoad::Clear`.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_scheme_render_pass_begin(struct GoldyScheme *scheme,
                                                const char *label,
                                                const struct GoldySchemeRenderTargetLease *lease,
                                                enum GoldyTargetLoad load,
                                                struct GoldyColor clear_color);

// Clear the depth attachment in the active render pass.
//
// # Safety
// `scheme` must be valid.
enum GoldyResult goldy_scheme_render_pass_clear_depth(struct GoldyScheme *scheme, float depth);

// Draw non-indexed primitives in the active render pass.
//
// # Safety
// `scheme` must be valid.
enum GoldyResult goldy_scheme_render_pass_draw(struct GoldyScheme *scheme,
                                               uint32_t first_vertex,
                                               uint32_t vertex_count,
                                               uint32_t first_instance,
                                               uint32_t instance_count);

// Draw a fullscreen triangle in the active render pass.
//
// # Safety
// `scheme` must be valid.
enum GoldyResult goldy_scheme_render_pass_draw_fullscreen(struct GoldyScheme *scheme);

// Draw indexed primitives in the active render pass.
//
// # Safety
// `scheme` must be valid.
enum GoldyResult goldy_scheme_render_pass_draw_indexed(struct GoldyScheme *scheme,
                                                       uint32_t first_index,
                                                       uint32_t index_count,
                                                       int32_t base_vertex,
                                                       uint32_t first_instance,
                                                       uint32_t instance_count);

// Finalize the active render pass and append it to the scheme.
//
// # Safety
// `scheme` must be valid.
enum GoldyResult goldy_scheme_render_pass_finish(struct GoldyScheme *scheme);

// Bind an index buffer parcel for the active render pass.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_scheme_render_pass_set_index_buffer(struct GoldyScheme *scheme,
                                                           const struct GoldyParcel *parcel,
                                                           enum GoldyIndexFormat format);

// Set the render pipeline for the active render pass.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_scheme_render_pass_set_pipeline(struct GoldyScheme *scheme,
                                                       const struct GoldyRenderPipeline *pipeline);

// Bind a vertex buffer slot from a retained buffer parcel.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_scheme_render_pass_set_vertex_buffer_parcel(struct GoldyScheme *scheme,
                                                                   uint32_t slot,
                                                                   const struct GoldyParcel *parcel);

// Declare a buffer unit dependency for the active render pass.
enum GoldyResult goldy_scheme_render_pass_with_buffer_unit(struct GoldyScheme *scheme,
                                                           const struct GoldyBuffer *buffer,
                                                           uint32_t unit,
                                                           enum GoldyNodeAccess access);

// Bind one field of a partitioned retained buffer to the active render pass.
enum GoldyResult goldy_scheme_render_pass_with_field(struct GoldyScheme *scheme,
                                                     const struct GoldyBuffer *buffer,
                                                     uint32_t unit,
                                                     enum GoldyNodeAccess access);

// Declare a graph dependency on a retained parcel for the active render pass.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_scheme_render_pass_with_parcel(struct GoldyScheme *scheme,
                                                      const struct GoldyParcel *parcel,
                                                      enum GoldyNodeAccess access);

// Destroy a render-target lease handle.
//
// Does not remove the lease from the scheme; the backing remains until the scheme is dropped.
//
// # Safety
// `lease` must be valid and not used after this call.
void goldy_scheme_render_target_lease_destroy(struct GoldySchemeRenderTargetLease *lease);

// Submission outcome counters.
//
// # Safety
// `scheme` and `out_stats` must be valid.
enum GoldyResult goldy_scheme_replay_stats(const struct GoldyScheme *scheme,
                                           struct GoldyReplayStats *out_stats);

// Destroy a submission token from [`goldy_scheme_submit`].
//
// # Safety
// `submission` must be valid and not used after this call.
void goldy_scheme_submission_destroy(struct GoldySchemeSubmission *submission);

// Timeline value for this submission (for debugging only).
//
// # Safety
// `submission` must be valid.
uint64_t goldy_scheme_submission_timeline_value(const struct GoldySchemeSubmission *submission);

// Block until the GPU work for `submission` has completed.
//
// Prefer [`goldy_read_grant_consume`] when verifying compute output through a grant.
//
// # Safety
// `ctx` and `submission` must be valid.
enum GoldyResult goldy_scheme_submission_wait(const struct GoldyContext *ctx,
                                              const struct GoldySchemeSubmission *submission);

// Submit the scheme and return a heap-allocated per-submission [`GoldySchemeSubmission`].
//
// Does not block. The caller owns `*out_submission` and must call
// [`goldy_scheme_submission_destroy`]. To read bytes from a recorded grant, use
// [`goldy_read_grant_consume`] with a [`GoldyReadGrant`] from [`goldy_scheme_grant_read`].
//
// # Safety
// `scheme` and `out_submission` must be valid; `*out_submission` is written on success.
enum GoldyResult goldy_scheme_submit(struct GoldyScheme *scheme,
                                     struct GoldySchemeSubmission **out_submission);

// Get the built-in vertex color 2D shader source.
//
// Returns a pointer to a static null-terminated string.
const char *goldy_shader_builtin_vertex_color_2d(void);

// Create a shader module from Slang source.
//
// Returns a pointer to the shader module, or null on failure.
//
// # Safety
// The device pointer must be valid.
// The source must be a valid null-terminated UTF-8 string.
struct GoldyShaderModule *goldy_shader_create(const struct GoldyDevice *device, const char *source);

// Destroy a shader module.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_shader_destroy(struct GoldyShaderModule *shader);

// Record texture → surface copy and return a transaction.
//
// # Safety
// All pointers must be valid.
struct GoldyTransaction *goldy_surface_exchange_bind(const struct GoldySurfaceExchange *exchange,
                                                     struct GoldyScheme *scheme,
                                                     const struct GoldyTexture *source);

// Register present without a copy; scheme writes the drawable directly.
//
// Writes lease and transaction into `out`.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_surface_exchange_bind_destination(const struct GoldySurfaceExchange *exchange,
                                                         struct GoldyScheme *scheme,
                                                         struct GoldySurfaceExchangeBindDestinationOut *out);

// Record offscreen render-target → surface copy and return a transaction.
//
// # Safety
// All pointers must be valid.
struct GoldyTransaction *goldy_surface_exchange_bind_render_target(const struct GoldySurfaceExchange *exchange,
                                                                   struct GoldyScheme *scheme,
                                                                   const struct GoldySchemeRenderTargetLease *src_lease);

// Create a surface exchange from an AppKit `NSView` pointer.
//
// # Safety
// `ctx` must be valid. `ns_view` must be a valid `NSView*` for the window's content view.
struct GoldySurfaceExchange *goldy_surface_exchange_create_appkit(const struct GoldyContext *ctx,
                                                                  void *ns_view,
                                                                  uint32_t depth);

// Create a surface exchange from Wayland `wl_display` and `wl_surface` pointers.
//
// # Safety
// `ctx` must be valid. `display` and `surface` must be valid Wayland handles.
struct GoldySurfaceExchange *goldy_surface_exchange_create_wayland(const struct GoldyContext *ctx,
                                                                   void *display,
                                                                   void *surface,
                                                                   uint32_t depth);

// Create a surface exchange from a Win32 HWND.
//
// # Safety
// `ctx` must be valid. `hwnd` must be a valid Win32 window handle.
struct GoldySurfaceExchange *goldy_surface_exchange_create_win32(const struct GoldyContext *ctx,
                                                                 void *hwnd,
                                                                 uint32_t depth);

// Destroy a surface exchange.
//
// # Safety
// `exchange` must be valid and not used after this call.
void goldy_surface_exchange_destroy(struct GoldySurfaceExchange *exchange);

// Surface format.
//
// # Safety
// `exchange` must be valid.
enum GoldyTextureFormat goldy_surface_exchange_format(const struct GoldySurfaceExchange *exchange);

// Current backing generation (advances on resize / present-mode change).
//
// # Safety
// `exchange` must be valid.
uint64_t goldy_surface_exchange_generation(const struct GoldySurfaceExchange *exchange);

// Current drawable height.
//
// # Safety
// `exchange` must be valid.
uint32_t goldy_surface_exchange_height(const struct GoldySurfaceExchange *exchange);

// Acquire a stable present lease (prefer exchange bind helpers for new code).
//
// Returns a heap-allocated lease handle; destroy with [`goldy_present_lease_destroy`].
//
// # Safety
// `exchange` must be valid.
struct GoldyPresentLease *goldy_surface_exchange_lease(const struct GoldySurfaceExchange *exchange);

// Resize the underlying swapchain.
//
// # Safety
// `exchange` must be valid.
enum GoldyResult goldy_surface_exchange_resize(struct GoldySurfaceExchange *exchange,
                                               uint32_t width,
                                               uint32_t height);

// Current drawable width.
//
// # Safety
// `exchange` must be valid.
uint32_t goldy_surface_exchange_width(const struct GoldySurfaceExchange *exchange);

uint64_t goldy_texture_byte_size(const struct GoldyTexture *texture);

void goldy_texture_destroy(struct GoldyTexture *texture);

// Binding id for this transaction within its scheme.
//
// # Safety
// `transaction` must be valid.
uint32_t goldy_transaction_binding_id(const struct GoldyTransaction *transaction);

// Extract this transaction's claim from a successful submission.
//
// Returns a heap-allocated claim; destroy with [`goldy_claim_destroy`].
//
// # Safety
// All pointers must be valid.
struct GoldyClaim *goldy_transaction_claim(const struct GoldyTransaction *transaction,
                                           struct GoldySchemeSubmission *submission);

// Destroy a transaction handle.
//
// # Safety
// `transaction` must be valid and not used after this call.
void goldy_transaction_destroy(struct GoldyTransaction *transaction);

// Backing generation snapshotted at claim time.
//
// # Safety
// `transaction` must be valid.
uint64_t goldy_transaction_generation(const struct GoldyTransaction *transaction);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GOLDY_H */
