/*
 * Goldy GPU Library - C API Header
 * 
 * Auto-generated by cbindgen. Do not edit manually.
 * 
 * LGPL-2.1-or-later - Copyright (c) 2025-2026 Mohamed Koubaa
 * 
 * This header provides the C API for the Goldy GPU library.
 * For C++ RAII wrappers, include goldy.hpp instead.
 */


#ifndef GOLDY_H
#define GOLDY_H

/* Generated with cbindgen:0.29.2 */

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Data access pattern for buffers.
//
// - `Scattered`: Any thread, any address, read/write. No coherence assumptions.
// - `Broadcast`: All threads read same address. Hardware broadcast optimization.
typedef enum GoldyBufferKind {
    // Any thread, any address, read/write (StructuredBuffer, RWStructuredBuffer).
    GOLDY_BUFFER_KIND_SCATTERED = 0,
    // All threads same address, broadcast optimized (ConstantBuffer).
    GOLDY_BUFFER_KIND_BROADCAST = 1,
} GoldyBufferKind;

// Result codes for FFI functions.
typedef enum GoldyResult {
    // Operation succeeded.
    GOLDY_RESULT_OK = 0,
    // Invalid argument provided.
    GOLDY_RESULT_INVALID_ARGUMENT = 1,
    // Null pointer provided.
    GOLDY_RESULT_NULL_POINTER = 2,
    // GPU operation failed.
    GOLDY_RESULT_GPU_ERROR = 3,
    // Shader compilation failed.
    GOLDY_RESULT_SHADER_ERROR = 4,
    // Resource creation failed.
    GOLDY_RESULT_RESOURCE_ERROR = 5,
    // Internal error.
    GOLDY_RESULT_INTERNAL_ERROR = 6,
} GoldyResult;

// Shader resource binding access (SRV vs UAV).
typedef enum GoldyResourceAccess {
    GOLDY_RESOURCE_ACCESS_READ = 0,
    GOLDY_RESOURCE_ACCESS_WRITE = 1,
    GOLDY_RESOURCE_ACCESS_READ_WRITE = 2,
} GoldyResourceAccess;

// Graphics backend type.
typedef enum GoldyBackendType {
    GOLDY_BACKEND_TYPE_VULKAN = 0,
    GOLDY_BACKEND_TYPE_METAL = 1,
    GOLDY_BACKEND_TYPE_DX12 = 2,
    GOLDY_BACKEND_TYPE_WEB_GPU = 3,
} GoldyBackendType;

// GPU device type.
typedef enum GoldyDeviceType {
    GOLDY_DEVICE_TYPE_DISCRETE_GPU = 0,
    GOLDY_DEVICE_TYPE_INTEGRATED_GPU = 1,
    GOLDY_DEVICE_TYPE_CPU = 2,
    GOLDY_DEVICE_TYPE_OTHER = 3,
} GoldyDeviceType;

// Vertex format.
typedef enum GoldyVertexFormat {
    GOLDY_VERTEX_FORMAT_FLOAT32 = 0,
    GOLDY_VERTEX_FORMAT_FLOAT32X2 = 1,
    GOLDY_VERTEX_FORMAT_FLOAT32X3 = 2,
    GOLDY_VERTEX_FORMAT_FLOAT32X4 = 3,
    GOLDY_VERTEX_FORMAT_UINT32 = 4,
    GOLDY_VERTEX_FORMAT_SINT32 = 5,
    GOLDY_VERTEX_FORMAT_UINT8X4 = 6,
    GOLDY_VERTEX_FORMAT_UNORM8X4 = 7,
} GoldyVertexFormat;

// Primitive topology.
typedef enum GoldyPrimitiveTopology {
    GOLDY_PRIMITIVE_TOPOLOGY_POINT_LIST = 0,
    GOLDY_PRIMITIVE_TOPOLOGY_LINE_LIST = 1,
    GOLDY_PRIMITIVE_TOPOLOGY_LINE_STRIP = 2,
    GOLDY_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST = 3,
    GOLDY_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP = 4,
} GoldyPrimitiveTopology;

// Texture format.
typedef enum GoldyTextureFormat {
    GOLDY_TEXTURE_FORMAT_RGBA8_UNORM_SRGB = 0,
    GOLDY_TEXTURE_FORMAT_RGBA8_UNORM = 1,
    GOLDY_TEXTURE_FORMAT_BGRA8_UNORM_SRGB = 2,
    GOLDY_TEXTURE_FORMAT_BGRA8_UNORM = 3,
    GOLDY_TEXTURE_FORMAT_RGBA16_FLOAT = 4,
    GOLDY_TEXTURE_FORMAT_RGBA32_FLOAT = 5,
    GOLDY_TEXTURE_FORMAT_R8_UNORM = 6,
    GOLDY_TEXTURE_FORMAT_RG8_UNORM = 7,
} GoldyTextureFormat;

// Depth format.
typedef enum GoldyDepthFormat {
    GOLDY_DEPTH_FORMAT_DEPTH16_UNORM = 0,
    GOLDY_DEPTH_FORMAT_DEPTH24_PLUS = 1,
    GOLDY_DEPTH_FORMAT_DEPTH24_PLUS_STENCIL8 = 2,
    GOLDY_DEPTH_FORMAT_DEPTH32_FLOAT = 3,
    GOLDY_DEPTH_FORMAT_DEPTH32_FLOAT_STENCIL8 = 4,
} GoldyDepthFormat;

// Comparison function for depth testing.
typedef enum GoldyCompareFunction {
    GOLDY_COMPARE_FUNCTION_NEVER = 0,
    GOLDY_COMPARE_FUNCTION_LESS = 1,
    GOLDY_COMPARE_FUNCTION_EQUAL = 2,
    GOLDY_COMPARE_FUNCTION_LESS_EQUAL = 3,
    GOLDY_COMPARE_FUNCTION_GREATER = 4,
    GOLDY_COMPARE_FUNCTION_NOT_EQUAL = 5,
    GOLDY_COMPARE_FUNCTION_GREATER_EQUAL = 6,
    GOLDY_COMPARE_FUNCTION_ALWAYS = 7,
} GoldyCompareFunction;

// Texture addressing mode.
typedef enum GoldyAddressMode {
    GOLDY_ADDRESS_MODE_CLAMP_TO_EDGE = 0,
    GOLDY_ADDRESS_MODE_REPEAT = 1,
    GOLDY_ADDRESS_MODE_MIRROR_REPEAT = 2,
} GoldyAddressMode;

// Texture filter mode.
typedef enum GoldyFilterMode {
    GOLDY_FILTER_MODE_NEAREST = 0,
    GOLDY_FILTER_MODE_LINEAR = 1,
} GoldyFilterMode;

// Per-node resource access for task graph bindings.
typedef enum GoldyNodeAccess {
    GOLDY_NODE_ACCESS_READ = 0,
    GOLDY_NODE_ACCESS_WRITE = 1,
    GOLDY_NODE_ACCESS_READ_WRITE = 2,
} GoldyNodeAccess;

// Index format.
typedef enum GoldyIndexFormat {
    GOLDY_INDEX_FORMAT_UINT16 = 0,
    GOLDY_INDEX_FORMAT_UINT32 = 1,
} GoldyIndexFormat;

// Spatial access pattern for textures.
//
// - `Interpolated`: Hardware filtering between neighbors (texture units).
// - `Direct`: Direct 2D/3D indexing, no filtering, read/write.
// - `DirectInterpolated`: Both storage (UAV) and sampled (SRV) access on the same texture.
typedef enum GoldyTextureKind {
    // Hardware filtering between neighbors (Texture2D with sampler).
    GOLDY_TEXTURE_KIND_INTERPOLATED = 0,
    // Direct 2D/3D indexing, no filtering (RWTexture2D).
    GOLDY_TEXTURE_KIND_DIRECT = 1,
    // Both UAV (storage/write) and SRV (sampled/read) access on the same texture.
    GOLDY_TEXTURE_KIND_DIRECT_INTERPOLATED = 2,
} GoldyTextureKind;

// Opaque handle to a Goldy Buffer.
typedef struct GoldyBuffer GoldyBuffer;

// Opaque handle to a Goldy BufferPool.
typedef struct GoldyBufferPool GoldyBufferPool;

// Opaque handle to a Goldy BufferView (sub-range of a pool backing buffer).
typedef struct GoldyBufferView GoldyBufferView;

// Opaque handle to a Goldy ComputePipeline.
typedef struct GoldyComputePipeline GoldyComputePipeline;

// Opaque handle to a Goldy Device.
typedef struct GoldyDevice GoldyDevice;

// Opaque handle to a Goldy Instance.
typedef struct GoldyInstance GoldyInstance;

// Opaque handle to a Goldy RenderPipeline.
typedef struct GoldyRenderPipeline GoldyRenderPipeline;

// Opaque handle to a Goldy RenderTarget.
typedef struct GoldyRenderTarget GoldyRenderTarget;

// Opaque handle to a Goldy Sampler.
typedef struct GoldySampler GoldySampler;

// Opaque handle to a Goldy ShaderModule.
typedef struct GoldyShaderModule GoldyShaderModule;

// Opaque handle to a Goldy Surface.
//
// Surface creation is platform-specific and typically done through
// higher-level bindings that can pass window handles.
typedef struct GoldySurface GoldySurface;

// Opaque handle to a Goldy SurfaceFrame.
typedef struct GoldySurfaceFrame GoldySurfaceFrame;

// Opaque handle to a Goldy TaskGraph.
typedef struct GoldyTaskGraph GoldyTaskGraph;

// Opaque handle to a Goldy Texture.
typedef struct GoldyTexture GoldyTexture;

// Adapter info.
typedef struct GoldyAdapterInfo {
    uint32_t id;
    enum GoldyDeviceType device_type;
    char name[256];
    char vendor[64];
} GoldyAdapterInfo;

// Vertex attribute description.
typedef struct GoldyVertexAttribute {
    uint32_t location;
    enum GoldyVertexFormat format;
    uint32_t offset;
} GoldyVertexAttribute;

// Render pipeline descriptor for FFI.
typedef struct GoldyRenderPipelineDesc {
    // Pointer to vertex attributes array.
    const struct GoldyVertexAttribute *vertex_attributes;
    // Number of vertex attributes.
    uint32_t vertex_attribute_count;
    // Stride in bytes between vertices.
    uint32_t vertex_stride;
    // Primitive topology.
    enum GoldyPrimitiveTopology topology;
    // Target texture format.
    enum GoldyTextureFormat target_format;
    // Whether depth testing is enabled.
    bool depth_enabled;
    // Depth format (only used if depth_enabled is true).
    enum GoldyDepthFormat depth_format;
    // Whether to write depth values.
    bool depth_write_enabled;
    // Depth comparison function.
    enum GoldyCompareFunction depth_compare;
} GoldyRenderPipelineDesc;

// Sampler descriptor.
typedef struct GoldySamplerDesc {
    enum GoldyAddressMode address_mode_u;
    enum GoldyAddressMode address_mode_v;
    enum GoldyAddressMode address_mode_w;
    enum GoldyFilterMode mag_filter;
    enum GoldyFilterMode min_filter;
    enum GoldyFilterMode mipmap_filter;
    float max_anisotropy;
    float lod_min_clamp;
    float lod_max_clamp;
} GoldySamplerDesc;

// Opaque token returned by [`goldy_task_graph_declare_swapchain_output`].
//
// Carries no data; exists for type safety at the C ABI boundary.
typedef struct GoldySwapchainOutput {
    uint8_t _private[0];
} GoldySwapchainOutput;

// RGBA color with floating point components (0.0 - 1.0).
typedef struct GoldyColor {
    float r;
    float g;
    float b;
    float a;
} GoldyColor;

// Texture flags for copy and render operations.
typedef struct GoldyTextureFlags {
    uint32_t _0;
} GoldyTextureFlags;
#define GoldyTextureFlags_NONE (GoldyTextureFlags){ ._0 = 0 }
#define GoldyTextureFlags_COPY_SRC (GoldyTextureFlags){ ._0 = (1 << 0) }
#define GoldyTextureFlags_COPY_DST (GoldyTextureFlags){ ._0 = (1 << 1) }
#define GoldyTextureFlags_RENDER_TARGET (GoldyTextureFlags){ ._0 = (1 << 2) }

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Get the buffer's access pattern.
//
// # Safety
// The buffer pointer must be valid.
enum GoldyBufferKind goldy_buffer_access(const struct GoldyBuffer *buffer);

// Create a new buffer with the specified access pattern.
//
// # Access Patterns
// - `Scattered` (0): Any thread can access any address (StructuredBuffer, RWStructuredBuffer)
// - `Broadcast` (1): All threads read same address (ConstantBuffer)
//
// Returns a pointer to the buffer, or null on failure.
//
// # Safety
// The device pointer must be valid.
struct GoldyBuffer *goldy_buffer_create(const struct GoldyDevice *device,
                                        uint64_t size,
                                        enum GoldyBufferKind access);

// Create a buffer initialized with data.
//
// See `goldy_buffer_create` for access pattern documentation.
//
// Returns a pointer to the buffer, or null on failure.
//
// # Safety
// The device pointer must be valid.
// The data pointer must point to at least `size` bytes.
struct GoldyBuffer *goldy_buffer_create_with_data(const struct GoldyDevice *device,
                                                  const uint8_t *data,
                                                  size_t size,
                                                  enum GoldyBufferKind access);

// Create a buffer initialized with data and an explicit element stride.
//
// Use stride `4` for `uint`/`float` scattered buffers; stride `1` for raw byte blobs.
//
// # Safety
// The device pointer must be valid.
// The data pointer must point to at least `size` bytes.
struct GoldyBuffer *goldy_buffer_create_with_data_stride(const struct GoldyDevice *device,
                                                         const uint8_t *data,
                                                         size_t size,
                                                         enum GoldyBufferKind access,
                                                         uint32_t element_stride);

// Destroy a buffer.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_buffer_destroy(struct GoldyBuffer *buffer);

// Allocate `count` u32 elements from the pool.
//
// Returns a heap-allocated view handle, or null on failure.
//
// # Safety
// The pool pointer must be valid.
struct GoldyBufferView *goldy_buffer_pool_alloc_u32(struct GoldyBufferPool *pool, uint64_t count);

// Create a buffer pool with the given total capacity in bytes.
//
// # Safety
// The device pointer must be valid.
struct GoldyBufferPool *goldy_buffer_pool_create(const struct GoldyDevice *device,
                                                 uint64_t capacity);

// Destroy a buffer pool and its views.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_buffer_pool_destroy(struct GoldyBufferPool *pool);

// Write raw bytes into the pool's backing buffer at a byte offset.
//
// # Safety
// The pool pointer must be valid. `data` must point to at least `size` bytes.
enum GoldyResult goldy_buffer_pool_write_backing(const struct GoldyBufferPool *pool,
                                                 uint64_t byte_offset,
                                                 const uint8_t *data,
                                                 size_t size);

// Read buffer contents to CPU memory.
//
// # Safety
// All pointers must be valid. `output` must point to at least `output_size` bytes.
enum GoldyResult goldy_buffer_read_to_cpu(const struct GoldyBuffer *buffer,
                                          const struct GoldyDevice *device,
                                          uint8_t *output,
                                          size_t output_size);

// Bindless resource slot index for shader binding.
//
// Returns `u32::MAX` if the index is unavailable.
//
// # Safety
// The buffer pointer must be valid.
uint32_t goldy_buffer_resource_index(const struct GoldyBuffer *buffer,
                                     enum GoldyResourceAccess access);

// Get the buffer size in bytes.
//
// # Safety
// The buffer pointer must be valid.
uint64_t goldy_buffer_size(const struct GoldyBuffer *buffer);

// Destroy a buffer view.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_buffer_view_destroy(struct GoldyBufferView *view);

// View offset within the parent buffer in bytes.
//
// # Safety
// The view pointer must be valid.
uint64_t goldy_buffer_view_offset(const struct GoldyBufferView *view);

// Bindless resource slot index for shader binding.
//
// Returns `u32::MAX` if the index is unavailable.
//
// # Safety
// The view pointer must be valid.
uint32_t goldy_buffer_view_resource_index(const struct GoldyBufferView *view,
                                          enum GoldyResourceAccess access);

// View size in bytes.
//
// # Safety
// The view pointer must be valid.
uint64_t goldy_buffer_view_size(const struct GoldyBufferView *view);

// Write u32 cells into the view (`data` is `count * 4` bytes).
//
// # Safety
// The view pointer must be valid. `data` must point to at least `count * 4` bytes.
enum GoldyResult goldy_buffer_view_write_u32(const struct GoldyBufferView *view,
                                             const uint32_t *data,
                                             size_t count);

// Write data to a buffer.
//
// # Safety
// The buffer pointer must be valid.
// The data pointer must point to at least `size` bytes.
enum GoldyResult goldy_buffer_write(const struct GoldyBuffer *buffer,
                                    uint64_t offset,
                                    const uint8_t *data,
                                    size_t size);

// Clear the last error message.
void goldy_clear_error(void);

// Create a new compute pipeline.
//
// Returns a pointer to the pipeline, or null on failure.
//
// # Safety
// All pointers must be valid.
struct GoldyComputePipeline *goldy_compute_pipeline_create(const struct GoldyDevice *device,
                                                           const struct GoldyShaderModule *compute_shader);

// Destroy a compute pipeline.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_compute_pipeline_destroy(struct GoldyComputePipeline *pipeline);

// Get the adapter ID this device was created on.
//
// # Safety
// The device pointer must be valid.
uint32_t goldy_device_adapter_id(const struct GoldyDevice *device);

// Destroy a device.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_device_destroy(struct GoldyDevice *device);

// Check if a shader library is registered.
//
// # Safety
// The device pointer and name must be valid.
bool goldy_device_has_library(const struct GoldyDevice *device, const char *name);

// Check if the device is still valid.
//
// # Safety
// The device pointer must be valid.
bool goldy_device_is_valid(const struct GoldyDevice *device);

// Get the last error message.
//
// Returns a pointer to a null-terminated string. The pointer is valid until
// the next FFI call on the same thread.
//
// Returns null if no error has occurred.
const char *goldy_get_last_error(void);

// Get the number of available adapters.
//
// # Safety
// The instance pointer must be valid.
uint32_t goldy_instance_adapter_count(const struct GoldyInstance *instance);

// Get the backend type of an instance.
//
// # Safety
// The instance pointer must be valid.
enum GoldyBackendType goldy_instance_backend_type(const struct GoldyInstance *instance);

// Create a new Goldy instance.
//
// Returns a pointer to the instance, or null on failure.
// Call `goldy_get_last_error()` to get the error message.
struct GoldyInstance *goldy_instance_create(void);

// Create a device for a specific adapter ID.
//
// Returns a pointer to the device, or null on failure.
//
// # Safety
// The instance pointer must be valid.
struct GoldyDevice *goldy_instance_create_device_for_adapter(const struct GoldyInstance *instance,
                                                             uint32_t adapter_id);

// Destroy an instance.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_instance_destroy(struct GoldyInstance *instance);

// Get adapter info at the given index.
//
// # Safety
// The instance pointer must be valid.
// The info pointer must point to a valid GoldyAdapterInfo struct.
enum GoldyResult goldy_instance_get_adapter(const struct GoldyInstance *instance,
                                            uint32_t index,
                                            struct GoldyAdapterInfo *info);

// Create a new render pipeline.
//
// Returns a pointer to the pipeline, or null on failure.
//
// # Safety
// All pointers must be valid.
struct GoldyRenderPipeline *goldy_render_pipeline_create(const struct GoldyDevice *device,
                                                         const struct GoldyShaderModule *vertex_shader,
                                                         const struct GoldyShaderModule *fragment_shader,
                                                         const struct GoldyRenderPipelineDesc *desc);

// Destroy a render pipeline.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_render_pipeline_destroy(struct GoldyRenderPipeline *pipeline);

// Get the buffer size in bytes.
//
// # Safety
// The target pointer must be valid.
size_t goldy_render_target_buffer_size(const struct GoldyRenderTarget *target);

// Create a new render target without depth buffer.
//
// Returns a pointer to the render target, or null on failure.
//
// # Safety
// The device pointer must be valid.
struct GoldyRenderTarget *goldy_render_target_create(const struct GoldyDevice *device,
                                                     uint32_t width,
                                                     uint32_t height,
                                                     enum GoldyTextureFormat format);

// Create a new render target with depth buffer.
//
// Returns a pointer to the render target, or null on failure.
//
// # Safety
// The device pointer must be valid.
struct GoldyRenderTarget *goldy_render_target_create_with_depth(const struct GoldyDevice *device,
                                                                uint32_t width,
                                                                uint32_t height,
                                                                enum GoldyTextureFormat color_format,
                                                                enum GoldyDepthFormat depth_format);

// Destroy a render target.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_render_target_destroy(struct GoldyRenderTarget *target);

// Get the render target format.
//
// # Safety
// The target pointer must be valid.
enum GoldyTextureFormat goldy_render_target_format(const struct GoldyRenderTarget *target);

// Check if the render target has a depth buffer.
//
// # Safety
// The target pointer must be valid.
bool goldy_render_target_has_depth(const struct GoldyRenderTarget *target);

// Get the render target height.
//
// # Safety
// The target pointer must be valid.
uint32_t goldy_render_target_height(const struct GoldyRenderTarget *target);

// Read the rendered pixels to a CPU buffer.
//
// # Safety
// The target pointer must be valid.
// The output pointer must point to a buffer of at least `goldy_render_target_buffer_size()` bytes.
enum GoldyResult goldy_render_target_read_to_buffer(const struct GoldyRenderTarget *target,
                                                    uint8_t *output,
                                                    size_t output_size);

// Get the render target width.
//
// # Safety
// The target pointer must be valid.
uint32_t goldy_render_target_width(const struct GoldyRenderTarget *target);

// Create a new sampler with the given descriptor.
//
// Returns a pointer to the sampler, or null on failure.
//
// # Safety
// All pointers must be valid.
struct GoldySampler *goldy_sampler_create(const struct GoldyDevice *device,
                                          const struct GoldySamplerDesc *desc);

// Create a sampler with default settings.
//
// Returns a pointer to the sampler, or null on failure.
//
// # Safety
// The device pointer must be valid.
struct GoldySampler *goldy_sampler_create_default(const struct GoldyDevice *device);

// Destroy a sampler.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_sampler_destroy(struct GoldySampler *sampler);

// Get the built-in vertex color 2D shader source.
//
// Returns a pointer to a static null-terminated string.
const char *goldy_shader_builtin_vertex_color_2d(void);

// Create a shader module from Slang source.
//
// Returns a pointer to the shader module, or null on failure.
//
// # Safety
// The device pointer must be valid.
// The source must be a valid null-terminated UTF-8 string.
struct GoldyShaderModule *goldy_shader_create(const struct GoldyDevice *device, const char *source);

// Destroy a shader module.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_shader_destroy(struct GoldyShaderModule *shader);

// Acquire the next frame from the surface.
//
// Returns a pointer to the frame, or null on failure.
//
// # Safety
// The surface pointer must be valid.
struct GoldySurfaceFrame *goldy_surface_acquire(const struct GoldySurface *surface);

// Create a surface from an AppKit `NSView` pointer.
//
// # Safety
// - `device` must be valid.
// - `ns_view` must be a valid `NSView*` for the window's content view.
// - The view must outlive the surface.
struct GoldySurface *goldy_surface_create_appkit(const struct GoldyDevice *device, void *ns_view);

// Create a surface from Wayland `wl_display` and `wl_surface` pointers.
//
// # Safety
// - `device` must be valid.
// - `display` and `surface` must be valid Wayland handles for the window.
// - They must outlive the surface.
struct GoldySurface *goldy_surface_create_wayland(const struct GoldyDevice *device,
                                                  void *display,
                                                  void *surface);

// Create a surface from a Win32 HWND.
//
// # Arguments
// * `device` - A valid Goldy device pointer
// * `hwnd` - A Win32 HWND (window handle)
//
// # Returns
// A pointer to the created surface, or null on failure.
// Call `goldy_get_last_error()` for error details on failure.
//
// # Safety
// - The device pointer must be valid and not null.
// - The hwnd must be a valid Win32 window handle.
// - The window must remain valid for the lifetime of the surface.
struct GoldySurface *goldy_surface_create_win32(const struct GoldyDevice *device, void *hwnd);

// Destroy a surface.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_surface_destroy(struct GoldySurface *surface);

// Get the surface format.
//
// # Safety
// The surface pointer must be valid.
enum GoldyTextureFormat goldy_surface_format(const struct GoldySurface *surface);

// Get the frame height.
//
// # Safety
// The frame pointer must be valid.
uint32_t goldy_surface_frame_height(const struct GoldySurfaceFrame *frame);

// Get the frame width.
//
// # Safety
// The frame pointer must be valid.
uint32_t goldy_surface_frame_width(const struct GoldySurfaceFrame *frame);

// Get the surface height.
//
// # Safety
// The surface pointer must be valid.
uint32_t goldy_surface_height(const struct GoldySurface *surface);

// Present a frame to the surface.
//
// This consumes the frame.
//
// # Safety
// Both pointers must be valid.
// The frame is consumed and must not be used after this call.
enum GoldyResult goldy_surface_present(const struct GoldySurface *surface,
                                       struct GoldySurfaceFrame *frame);

// Resize the surface.
//
// # Safety
// The surface pointer must be valid.
enum GoldyResult goldy_surface_resize(struct GoldySurface *surface,
                                      uint32_t width,
                                      uint32_t height);

// Submit a task graph that writes to an already-acquired swapchain frame.
//
// The graph must include [`goldy_task_graph_declare_swapchain_output`] and
// [`goldy_task_graph_copy_render_target_to_swapchain`] (or another swapchain
// binding). Updates `frame` in place with any parcel stamp targets from the graph.
//
// # Safety
// All pointers must be valid. No render pass may be open on `graph`.
enum GoldyResult goldy_surface_submit_graph_to_frame(const struct GoldySurface *surface,
                                                     struct GoldyTaskGraph *graph,
                                                     struct GoldySurfaceFrame *frame);

// Get the surface width.
//
// # Safety
// The surface pointer must be valid.
uint32_t goldy_surface_width(const struct GoldySurface *surface);

// Reset the graph to empty while retaining internal capacity.
//
// # Safety
// The graph pointer must be valid.
enum GoldyResult goldy_task_graph_clear(struct GoldyTaskGraph *graph);

// Begin recording a compute dispatch node.
//
// Only one recorder (render pass or compute node) may be open at a time per graph.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_task_graph_compute_node_begin(struct GoldyTaskGraph *graph,
                                                     const char *label,
                                                     const struct GoldyComputePipeline *pipeline);

// Declare a buffer dependency for the active compute node.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_task_graph_compute_node_bind_buffer(struct GoldyTaskGraph *graph,
                                                           const struct GoldyBuffer *buffer,
                                                           enum GoldyNodeAccess access);

// Declare a buffer-view dependency for the active compute node.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_task_graph_compute_node_bind_buffer_view(struct GoldyTaskGraph *graph,
                                                                const struct GoldyBufferView *view,
                                                                enum GoldyNodeAccess access);

// Set bindless resource slot indices for the active compute node.
//
// # Safety
// All pointers must be valid. `indices` must contain `count` elements.
enum GoldyResult goldy_task_graph_compute_node_bind_resources_raw(struct GoldyTaskGraph *graph,
                                                                  const uint32_t *indices,
                                                                  uint32_t count);

// Finalize the active compute node with a direct dispatch.
//
// # Safety
// The graph pointer must be valid.
enum GoldyResult goldy_task_graph_compute_node_dispatch(struct GoldyTaskGraph *graph,
                                                        uint32_t workgroups_x,
                                                        uint32_t workgroups_y,
                                                        uint32_t workgroups_z);

// Add a render-target → swapchain blit node to the graph.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_task_graph_copy_render_target_to_swapchain(struct GoldyTaskGraph *graph,
                                                                  const struct GoldyRenderTarget *src,
                                                                  const struct GoldySwapchainOutput *_swapchain);

// Create a new task graph.
struct GoldyTaskGraph *goldy_task_graph_create(void);

// Declare that this graph will copy to the swapchain at submit time.
//
// Returns a pointer to a per-graph sentinel (not heap-allocated). The pointer is
// valid until the graph is destroyed and must be passed to
// [`goldy_task_graph_copy_render_target_to_swapchain`].
//
// # Safety
// The graph pointer must be valid.
struct GoldySwapchainOutput *goldy_task_graph_declare_swapchain_output(struct GoldyTaskGraph *graph);

// Destroy a task graph.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_task_graph_destroy(struct GoldyTaskGraph *graph);

// Analyze the graph, submit GPU work, and block until complete.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_task_graph_dispatch(struct GoldyTaskGraph *graph,
                                           const struct GoldyDevice *device);

// Number of task nodes recorded in the graph (for tests and diagnostics).
//
// # Safety
// The graph pointer must be valid.
uint32_t goldy_task_graph_len(const struct GoldyTaskGraph *graph);

// Begin recording an offscreen render pass on `target`.
//
// Only one render pass may be open at a time per graph.
//
// # Safety
// All pointers must be valid. `target` must outlive the graph recording session.
enum GoldyResult goldy_task_graph_render_pass_begin(struct GoldyTaskGraph *graph,
                                                    const char *label,
                                                    const struct GoldyRenderTarget *target);

// Declare a graph dependency on a buffer for the active render pass.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_task_graph_render_pass_bind_buffer(struct GoldyTaskGraph *graph,
                                                          const struct GoldyBuffer *buffer,
                                                          enum GoldyNodeAccess access);

// Declare a buffer-view dependency for the active render pass.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_task_graph_render_pass_bind_buffer_view(struct GoldyTaskGraph *graph,
                                                               const struct GoldyBufferView *view,
                                                               enum GoldyNodeAccess access);

// Bind shader resource slots from buffers for the active render pass.
//
// # Safety
// All pointers must be valid. `buffers` must contain `buffer_count` elements.
enum GoldyResult goldy_task_graph_render_pass_bind_resources(struct GoldyTaskGraph *graph,
                                                             const struct GoldyBuffer *const *buffers,
                                                             uint32_t buffer_count);

// Bind typed resource handles (category + index pairs) for the active render pass.
//
// `indices` is a flat array of u32 values: `[category0, index0, category1, index1, ...]`.
// Use `GoldyResourceCategory::Scattered` (0) for buffer views.
//
// # Safety
// All pointers must be valid. `indices` must contain `handle_count * 2` elements.
enum GoldyResult goldy_task_graph_render_pass_bind_resources_typed(struct GoldyTaskGraph *graph,
                                                                   const uint32_t *indices,
                                                                   uint32_t handle_count);

// Clear the color attachment in the active render pass.
//
// # Safety
// The graph pointer must be valid.
enum GoldyResult goldy_task_graph_render_pass_clear(struct GoldyTaskGraph *graph,
                                                    struct GoldyColor color);

// Clear the depth attachment in the active render pass.
//
// # Safety
// The graph pointer must be valid.
enum GoldyResult goldy_task_graph_render_pass_clear_depth(struct GoldyTaskGraph *graph,
                                                          float depth);

// Draw non-indexed primitives in the active render pass.
//
// # Safety
// The graph pointer must be valid.
enum GoldyResult goldy_task_graph_render_pass_draw(struct GoldyTaskGraph *graph,
                                                   uint32_t first_vertex,
                                                   uint32_t vertex_count,
                                                   uint32_t first_instance,
                                                   uint32_t instance_count);

// Draw a fullscreen triangle (3 vertices, 1 instance) in the active render pass.
//
// # Safety
// The graph pointer must be valid.
enum GoldyResult goldy_task_graph_render_pass_draw_fullscreen(struct GoldyTaskGraph *graph);

// Draw indexed primitives in the active render pass.
//
// # Safety
// The graph pointer must be valid.
enum GoldyResult goldy_task_graph_render_pass_draw_indexed(struct GoldyTaskGraph *graph,
                                                           uint32_t first_index,
                                                           uint32_t index_count,
                                                           int32_t base_vertex,
                                                           uint32_t first_instance,
                                                           uint32_t instance_count);

// Finalize the active render pass and append it to the graph.
//
// # Safety
// The graph pointer must be valid.
enum GoldyResult goldy_task_graph_render_pass_finish(struct GoldyTaskGraph *graph);

// Bind an index buffer for the active render pass.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_task_graph_render_pass_set_index_buffer(struct GoldyTaskGraph *graph,
                                                               const struct GoldyBuffer *buffer,
                                                               enum GoldyIndexFormat format);

// Set the render pipeline for the active render pass.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_task_graph_render_pass_set_pipeline(struct GoldyTaskGraph *graph,
                                                           const struct GoldyRenderPipeline *pipeline);

// Bind a vertex buffer slot for the active render pass.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_task_graph_render_pass_set_vertex_buffer(struct GoldyTaskGraph *graph,
                                                                uint32_t slot,
                                                                const struct GoldyBuffer *buffer);

// Bind a vertex buffer slot with a byte offset for the active render pass.
//
// # Safety
// All pointers must be valid.
enum GoldyResult goldy_task_graph_render_pass_set_vertex_buffer_offset(struct GoldyTaskGraph *graph,
                                                                       uint32_t slot,
                                                                       const struct GoldyBuffer *buffer,
                                                                       uint64_t offset);

// Add a CPU→GPU buffer upload node to the graph.
//
// # Safety
// All pointers must be valid. `data` must point to at least `size` bytes.
enum GoldyResult goldy_task_graph_write_buffer(struct GoldyTaskGraph *graph,
                                               const struct GoldyBuffer *buffer,
                                               uint64_t offset,
                                               const uint8_t *data,
                                               size_t size);

// Create a new texture with the specified spatial access pattern.
//
// # Access Patterns
// - `Interpolated` (0): Hardware filtering between neighbors (Texture2D with sampler)
// - `Direct` (1): Direct 2D indexing, no filtering (RWTexture2D)
//
// # Flags
// - `COPY_SRC` (1): Can be used as a copy source
// - `COPY_DST` (2): Can be used as a copy destination
// - `RENDER_TARGET` (4): Can be used as a render attachment
//
// Returns a pointer to the texture, or null on failure.
//
// # Safety
// The device pointer must be valid.
struct GoldyTexture *goldy_texture_create(const struct GoldyDevice *device,
                                          uint32_t width,
                                          uint32_t height,
                                          enum GoldyTextureFormat format,
                                          enum GoldyTextureKind access,
                                          struct GoldyTextureFlags flags);

// Destroy a texture.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_texture_destroy(struct GoldyTexture *texture);

// Get the texture format.
//
// # Safety
// The texture pointer must be valid.
enum GoldyTextureFormat goldy_texture_format(const struct GoldyTexture *texture);

// Get the texture height.
//
// # Safety
// The texture pointer must be valid.
uint32_t goldy_texture_height(const struct GoldyTexture *texture);

// Get the texture width.
//
// # Safety
// The texture pointer must be valid.
uint32_t goldy_texture_width(const struct GoldyTexture *texture);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GOLDY_H */
