/*
 * Goldy GPU Library - C API Header
 * 
 * Auto-generated by cbindgen. Do not edit manually.
 * 
 * MIT License - Copyright (c) 2025 KOB3 Contributors
 * 
 * This header provides the C API for the Goldy GPU library.
 * For C++ RAII wrappers, include goldy.hpp instead.
 */


#ifndef GOLDY_H
#define GOLDY_H

/* Generated with cbindgen:0.28.0 */

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Texture addressing mode.
typedef enum GoldyAddressMode {
    GOLDY_ADDRESS_MODE_CLAMP_TO_EDGE = 0,
    GOLDY_ADDRESS_MODE_REPEAT = 1,
    GOLDY_ADDRESS_MODE_MIRROR_REPEAT = 2,
} GoldyAddressMode;

// Graphics backend type.
typedef enum GoldyBackendType {
    GOLDY_BACKEND_TYPE_VULKAN = 0,
    GOLDY_BACKEND_TYPE_METAL = 1,
    GOLDY_BACKEND_TYPE_DX12 = 2,
    GOLDY_BACKEND_TYPE_WEB_GPU = 3,
} GoldyBackendType;

// Binding type for bind groups.
typedef enum GoldyBindingType {
    GOLDY_BINDING_TYPE_UNIFORM_BUFFER = 0,
    GOLDY_BINDING_TYPE_STORAGE_BUFFER_READ_ONLY = 1,
    GOLDY_BINDING_TYPE_STORAGE_BUFFER_READ_WRITE = 2,
    GOLDY_BINDING_TYPE_TEXTURE = 3,
    GOLDY_BINDING_TYPE_SAMPLER = 4,
    GOLDY_BINDING_TYPE_STORAGE_TEXTURE = 5,
} GoldyBindingType;

// Comparison function for depth testing.
typedef enum GoldyCompareFunction {
    GOLDY_COMPARE_FUNCTION_NEVER = 0,
    GOLDY_COMPARE_FUNCTION_LESS = 1,
    GOLDY_COMPARE_FUNCTION_EQUAL = 2,
    GOLDY_COMPARE_FUNCTION_LESS_EQUAL = 3,
    GOLDY_COMPARE_FUNCTION_GREATER = 4,
    GOLDY_COMPARE_FUNCTION_NOT_EQUAL = 5,
    GOLDY_COMPARE_FUNCTION_GREATER_EQUAL = 6,
    GOLDY_COMPARE_FUNCTION_ALWAYS = 7,
} GoldyCompareFunction;

// Depth format.
typedef enum GoldyDepthFormat {
    GOLDY_DEPTH_FORMAT_DEPTH16_UNORM = 0,
    GOLDY_DEPTH_FORMAT_DEPTH24_PLUS = 1,
    GOLDY_DEPTH_FORMAT_DEPTH24_PLUS_STENCIL8 = 2,
    GOLDY_DEPTH_FORMAT_DEPTH32_FLOAT = 3,
    GOLDY_DEPTH_FORMAT_DEPTH32_FLOAT_STENCIL8 = 4,
} GoldyDepthFormat;

// GPU device type.
typedef enum GoldyDeviceType {
    GOLDY_DEVICE_TYPE_DISCRETE_GPU = 0,
    GOLDY_DEVICE_TYPE_INTEGRATED_GPU = 1,
    GOLDY_DEVICE_TYPE_CPU = 2,
    GOLDY_DEVICE_TYPE_OTHER = 3,
} GoldyDeviceType;

// Texture filter mode.
typedef enum GoldyFilterMode {
    GOLDY_FILTER_MODE_NEAREST = 0,
    GOLDY_FILTER_MODE_LINEAR = 1,
} GoldyFilterMode;

// Index format.
typedef enum GoldyIndexFormat {
    GOLDY_INDEX_FORMAT_UINT16 = 0,
    GOLDY_INDEX_FORMAT_UINT32 = 1,
} GoldyIndexFormat;

// Primitive topology.
typedef enum GoldyPrimitiveTopology {
    GOLDY_PRIMITIVE_TOPOLOGY_POINT_LIST = 0,
    GOLDY_PRIMITIVE_TOPOLOGY_LINE_LIST = 1,
    GOLDY_PRIMITIVE_TOPOLOGY_LINE_STRIP = 2,
    GOLDY_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST = 3,
    GOLDY_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP = 4,
} GoldyPrimitiveTopology;

// Result codes for FFI functions.
typedef enum GoldyResult {
    // Operation succeeded.
    GOLDY_RESULT_OK = 0,
    // Invalid argument provided.
    GOLDY_RESULT_INVALID_ARGUMENT = 1,
    // Null pointer provided.
    GOLDY_RESULT_NULL_POINTER = 2,
    // GPU operation failed.
    GOLDY_RESULT_GPU_ERROR = 3,
    // Shader compilation failed.
    GOLDY_RESULT_SHADER_ERROR = 4,
    // Resource creation failed.
    GOLDY_RESULT_RESOURCE_ERROR = 5,
    // Internal error.
    GOLDY_RESULT_INTERNAL_ERROR = 6,
} GoldyResult;

// Texture format.
typedef enum GoldyTextureFormat {
    GOLDY_TEXTURE_FORMAT_RGBA8_UNORM_SRGB = 0,
    GOLDY_TEXTURE_FORMAT_RGBA8_UNORM = 1,
    GOLDY_TEXTURE_FORMAT_BGRA8_UNORM_SRGB = 2,
    GOLDY_TEXTURE_FORMAT_BGRA8_UNORM = 3,
    GOLDY_TEXTURE_FORMAT_RGBA16_FLOAT = 4,
    GOLDY_TEXTURE_FORMAT_RGBA32_FLOAT = 5,
} GoldyTextureFormat;

// Vertex format.
typedef enum GoldyVertexFormat {
    GOLDY_VERTEX_FORMAT_FLOAT32 = 0,
    GOLDY_VERTEX_FORMAT_FLOAT32X2 = 1,
    GOLDY_VERTEX_FORMAT_FLOAT32X3 = 2,
    GOLDY_VERTEX_FORMAT_FLOAT32X4 = 3,
    GOLDY_VERTEX_FORMAT_UINT32 = 4,
    GOLDY_VERTEX_FORMAT_SINT32 = 5,
    GOLDY_VERTEX_FORMAT_UINT8X4 = 6,
    GOLDY_VERTEX_FORMAT_UNORM8X4 = 7,
} GoldyVertexFormat;

// Opaque handle to a Goldy BindGroup.
typedef struct GoldyBindGroup GoldyBindGroup;

// Opaque handle to a Goldy BindGroupLayout.
typedef struct GoldyBindGroupLayout GoldyBindGroupLayout;

// Opaque handle to a Goldy Buffer.
typedef struct GoldyBuffer GoldyBuffer;

// Opaque handle to a Goldy CommandEncoder.
typedef struct GoldyCommandEncoder GoldyCommandEncoder;

// Opaque handle to a Goldy ComputeEncoder.
typedef struct GoldyComputeEncoder GoldyComputeEncoder;

// Opaque handle to a Goldy ComputePipeline.
typedef struct GoldyComputePipeline GoldyComputePipeline;

// Opaque handle to a Goldy Device.
typedef struct GoldyDevice GoldyDevice;

// Opaque handle to a Goldy Instance.
typedef struct GoldyInstance GoldyInstance;

// Opaque handle to a Goldy RenderPipeline.
typedef struct GoldyRenderPipeline GoldyRenderPipeline;

// Opaque handle to a Goldy RenderTarget.
typedef struct GoldyRenderTarget GoldyRenderTarget;

// Opaque handle to a Goldy Sampler.
typedef struct GoldySampler GoldySampler;

// Opaque handle to a Goldy ShaderModule.
typedef struct GoldyShaderModule GoldyShaderModule;

// Opaque handle to a Goldy Surface.
//
// Surface creation is platform-specific and typically done through
// higher-level bindings that can pass window handles.
typedef struct GoldySurface GoldySurface;

// Opaque handle to a Goldy SurfaceFrame.
typedef struct GoldySurfaceFrame GoldySurfaceFrame;

// Opaque handle to a Goldy Texture.
typedef struct GoldyTexture GoldyTexture;

// Buffer binding descriptor.
typedef struct GoldyBufferBinding {
    uint32_t binding;
    const struct GoldyBuffer *buffer;
    uint64_t offset;
    // Size in bytes, or 0 for entire buffer.
    uint64_t size;
} GoldyBufferBinding;

// Texture binding descriptor.
typedef struct GoldyTextureBinding {
    uint32_t binding;
    const struct GoldyTexture *texture;
} GoldyTextureBinding;

// Sampler binding descriptor.
typedef struct GoldySamplerBinding {
    uint32_t binding;
    const struct GoldySampler *sampler;
} GoldySamplerBinding;

// Shader stages flags.
typedef struct GoldyShaderStages {
    uint32_t _0;
} GoldyShaderStages;
#define GoldyShaderStages_VERTEX (GoldyShaderStages){ ._0 = 1 }
#define GoldyShaderStages_FRAGMENT (GoldyShaderStages){ ._0 = 2 }
#define GoldyShaderStages_COMPUTE (GoldyShaderStages){ ._0 = 4 }
#define GoldyShaderStages_ALL (GoldyShaderStages){ ._0 = 7 }

// Bind group layout binding descriptor.
typedef struct GoldyBindGroupLayoutBinding {
    uint32_t binding;
    struct GoldyShaderStages visibility;
    enum GoldyBindingType binding_type;
} GoldyBindGroupLayoutBinding;

// Buffer usage flags.
typedef struct GoldyBufferUsage {
    uint32_t _0;
} GoldyBufferUsage;
#define GoldyBufferUsage_VERTEX (GoldyBufferUsage){ ._0 = (1 << 0) }
#define GoldyBufferUsage_INDEX (GoldyBufferUsage){ ._0 = (1 << 1) }
#define GoldyBufferUsage_UNIFORM (GoldyBufferUsage){ ._0 = (1 << 2) }
#define GoldyBufferUsage_STORAGE (GoldyBufferUsage){ ._0 = (1 << 3) }
#define GoldyBufferUsage_COPY_SRC (GoldyBufferUsage){ ._0 = (1 << 4) }
#define GoldyBufferUsage_COPY_DST (GoldyBufferUsage){ ._0 = (1 << 5) }

// RGBA color with floating point components (0.0 - 1.0).
typedef struct GoldyColor {
    float r;
    float g;
    float b;
    float a;
} GoldyColor;

// Adapter info.
typedef struct GoldyAdapterInfo {
    uint32_t id;
    enum GoldyDeviceType device_type;
    char name[256];
    char vendor[64];
} GoldyAdapterInfo;

// Vertex attribute description.
typedef struct GoldyVertexAttribute {
    uint32_t location;
    enum GoldyVertexFormat format;
    uint32_t offset;
} GoldyVertexAttribute;

// Render pipeline descriptor for FFI.
typedef struct GoldyRenderPipelineDesc {
    // Pointer to vertex attributes array.
    const struct GoldyVertexAttribute *vertex_attributes;
    // Number of vertex attributes.
    uint32_t vertex_attribute_count;
    // Stride in bytes between vertices.
    uint32_t vertex_stride;
    // Primitive topology.
    enum GoldyPrimitiveTopology topology;
    // Target texture format.
    enum GoldyTextureFormat target_format;
    // Pointer to bind group layouts array (can be null).
    const struct GoldyBindGroupLayout *const *bind_group_layouts;
    // Number of bind group layouts.
    uint32_t bind_group_layout_count;
    // Whether depth testing is enabled.
    bool depth_enabled;
    // Depth format (only used if depth_enabled is true).
    enum GoldyDepthFormat depth_format;
    // Whether to write depth values.
    bool depth_write_enabled;
    // Depth comparison function.
    enum GoldyCompareFunction depth_compare;
} GoldyRenderPipelineDesc;

// Sampler descriptor.
typedef struct GoldySamplerDesc {
    enum GoldyAddressMode address_mode_u;
    enum GoldyAddressMode address_mode_v;
    enum GoldyAddressMode address_mode_w;
    enum GoldyFilterMode mag_filter;
    enum GoldyFilterMode min_filter;
    enum GoldyFilterMode mipmap_filter;
    float max_anisotropy;
    float lod_min_clamp;
    float lod_max_clamp;
} GoldySamplerDesc;

// Texture usage flags.
typedef struct GoldyTextureUsage {
    uint32_t _0;
} GoldyTextureUsage;
#define GoldyTextureUsage_COPY_SRC (GoldyTextureUsage){ ._0 = (1 << 0) }
#define GoldyTextureUsage_COPY_DST (GoldyTextureUsage){ ._0 = (1 << 1) }
#define GoldyTextureUsage_SAMPLED (GoldyTextureUsage){ ._0 = (1 << 2) }
#define GoldyTextureUsage_STORAGE (GoldyTextureUsage){ ._0 = (1 << 3) }
#define GoldyTextureUsage_RENDER_TARGET (GoldyTextureUsage){ ._0 = (1 << 4) }

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Create a bind group with buffer bindings only.
//
// Returns a pointer to the bind group, or null on failure.
//
// # Safety
// All pointers must be valid.
struct GoldyBindGroup *goldy_bind_group_create(const struct GoldyDevice *device,
                                               const struct GoldyBindGroupLayout *layout,
                                               const struct GoldyBufferBinding *buffer_bindings,
                                               uint32_t buffer_binding_count);

// Create a bind group with buffers, textures, and samplers.
//
// Returns a pointer to the bind group, or null on failure.
//
// # Safety
// All pointers must be valid.
struct GoldyBindGroup *goldy_bind_group_create_with_resources(const struct GoldyDevice *device,
                                                              const struct GoldyBindGroupLayout *layout,
                                                              const struct GoldyBufferBinding *buffer_bindings,
                                                              uint32_t buffer_binding_count,
                                                              const struct GoldyTextureBinding *texture_bindings,
                                                              uint32_t texture_binding_count,
                                                              const struct GoldySamplerBinding *sampler_bindings,
                                                              uint32_t sampler_binding_count);

// Destroy a bind group.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_bind_group_destroy(struct GoldyBindGroup *bind_group);

// Create a bind group layout.
//
// Returns a pointer to the layout, or null on failure.
//
// # Safety
// All pointers must be valid.
struct GoldyBindGroupLayout *goldy_bind_group_layout_create(const struct GoldyDevice *device,
                                                            const struct GoldyBindGroupLayoutBinding *bindings,
                                                            uint32_t binding_count);

// Destroy a bind group layout.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_bind_group_layout_destroy(struct GoldyBindGroupLayout *layout);

// Create a new buffer.
//
// Returns a pointer to the buffer, or null on failure.
//
// # Safety
// The device pointer must be valid.
struct GoldyBuffer *goldy_buffer_create(const struct GoldyDevice *device,
                                        uint64_t size,
                                        struct GoldyBufferUsage usage);

// Create a buffer initialized with data.
//
// Returns a pointer to the buffer, or null on failure.
//
// # Safety
// The device pointer must be valid.
// The data pointer must point to at least `size` bytes.
struct GoldyBuffer *goldy_buffer_create_with_data(const struct GoldyDevice *device,
                                                  const uint8_t *data,
                                                  size_t size,
                                                  struct GoldyBufferUsage usage);

// Destroy a buffer.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_buffer_destroy(struct GoldyBuffer *buffer);

// Get the buffer size in bytes.
//
// # Safety
// The buffer pointer must be valid.
uint64_t goldy_buffer_size(const struct GoldyBuffer *buffer);

// Get the buffer usage flags.
//
// # Safety
// The buffer pointer must be valid.
struct GoldyBufferUsage goldy_buffer_usage(const struct GoldyBuffer *buffer);

// Write data to a buffer.
//
// # Safety
// The buffer pointer must be valid.
// The data pointer must point to at least `size` bytes.
enum GoldyResult goldy_buffer_write(const struct GoldyBuffer *buffer,
                                    uint64_t offset,
                                    const uint8_t *data,
                                    size_t size);

// Clear the last error message.
void goldy_clear_error(void);

// Create a new compute encoder.
struct GoldyComputeEncoder *goldy_compute_encoder_create(void);

// Destroy a compute encoder without dispatching.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_compute_encoder_destroy(struct GoldyComputeEncoder *encoder);

// Dispatch compute workgroups.
//
// # Safety
// The encoder pointer must be valid.
void goldy_compute_encoder_dispatch(struct GoldyComputeEncoder *encoder,
                                    uint32_t workgroups_x,
                                    uint32_t workgroups_y,
                                    uint32_t workgroups_z);

// Execute the compute commands on the device.
//
// # Safety
// Both pointers must be valid.
enum GoldyResult goldy_compute_encoder_execute(const struct GoldyComputeEncoder *encoder,
                                               const struct GoldyDevice *device);

// Set a bind group for compute.
//
// # Safety
// All pointers must be valid.
void goldy_compute_encoder_set_bind_group(struct GoldyComputeEncoder *encoder,
                                          uint32_t index,
                                          const struct GoldyBindGroup *bind_group);

// Set the compute pipeline.
//
// # Safety
// Both pointers must be valid.
void goldy_compute_encoder_set_pipeline(struct GoldyComputeEncoder *encoder,
                                        const struct GoldyComputePipeline *pipeline);

// Create a new compute pipeline.
//
// Returns a pointer to the pipeline, or null on failure.
//
// # Safety
// All pointers must be valid.
struct GoldyComputePipeline *goldy_compute_pipeline_create(const struct GoldyDevice *device,
                                                           const struct GoldyShaderModule *compute_shader,
                                                           const struct GoldyBindGroupLayout *const *bind_group_layouts,
                                                           uint32_t bind_group_layout_count);

// Destroy a compute pipeline.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_compute_pipeline_destroy(struct GoldyComputePipeline *pipeline);

// Get the adapter ID this device was created on.
//
// # Safety
// The device pointer must be valid.
uint32_t goldy_device_adapter_id(const struct GoldyDevice *device);

// Destroy a device.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_device_destroy(struct GoldyDevice *device);

// Check if a shader library is registered.
//
// # Safety
// The device pointer and name must be valid.
bool goldy_device_has_library(const struct GoldyDevice *device, const char *name);

// Check if the device is still valid.
//
// # Safety
// The device pointer must be valid.
bool goldy_device_is_valid(const struct GoldyDevice *device);

// Clear the color render target.
//
// # Safety
// The encoder pointer must be valid.
void goldy_encoder_clear(struct GoldyCommandEncoder *encoder, struct GoldyColor color);

// Clear the depth buffer.
//
// # Safety
// The encoder pointer must be valid.
void goldy_encoder_clear_depth(struct GoldyCommandEncoder *encoder, float depth);

// Create a new command encoder.
struct GoldyCommandEncoder *goldy_encoder_create(void);

// Destroy a command encoder without rendering.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_encoder_destroy(struct GoldyCommandEncoder *encoder);

// Draw primitives.
//
// # Safety
// The encoder pointer must be valid.
void goldy_encoder_draw(struct GoldyCommandEncoder *encoder,
                        uint32_t vertex_start,
                        uint32_t vertex_count,
                        uint32_t instance_start,
                        uint32_t instance_count);

// Draw indexed primitives.
//
// # Safety
// The encoder pointer must be valid.
void goldy_encoder_draw_indexed(struct GoldyCommandEncoder *encoder,
                                uint32_t index_start,
                                uint32_t index_count,
                                int32_t base_vertex,
                                uint32_t instance_start,
                                uint32_t instance_count);

// Set a bind group.
//
// # Safety
// All pointers must be valid.
void goldy_encoder_set_bind_group(struct GoldyCommandEncoder *encoder,
                                  uint32_t index,
                                  const struct GoldyBindGroup *bind_group);

// Set an index buffer.
//
// # Safety
// All pointers must be valid.
void goldy_encoder_set_index_buffer(struct GoldyCommandEncoder *encoder,
                                    const struct GoldyBuffer *buffer,
                                    enum GoldyIndexFormat format);

// Set the render pipeline.
//
// # Safety
// Both pointers must be valid.
void goldy_encoder_set_pipeline(struct GoldyCommandEncoder *encoder,
                                const struct GoldyRenderPipeline *pipeline);

// Set a vertex buffer.
//
// # Safety
// All pointers must be valid.
void goldy_encoder_set_vertex_buffer(struct GoldyCommandEncoder *encoder,
                                     uint32_t slot,
                                     const struct GoldyBuffer *buffer);

// Set a vertex buffer with offset.
//
// # Safety
// All pointers must be valid.
void goldy_encoder_set_vertex_buffer_offset(struct GoldyCommandEncoder *encoder,
                                            uint32_t slot,
                                            const struct GoldyBuffer *buffer,
                                            uint64_t offset);

// Get the last error message.
//
// Returns a pointer to a null-terminated string. The pointer is valid until
// the next FFI call on the same thread.
//
// Returns null if no error has occurred.
const char *goldy_get_last_error(void);

// Get the number of available adapters.
//
// # Safety
// The instance pointer must be valid.
uint32_t goldy_instance_adapter_count(const struct GoldyInstance *instance);

// Get the backend type of an instance.
//
// # Safety
// The instance pointer must be valid.
enum GoldyBackendType goldy_instance_backend_type(const struct GoldyInstance *instance);

// Create a new Goldy instance.
//
// Returns a pointer to the instance, or null on failure.
// Call `goldy_get_last_error()` to get the error message.
struct GoldyInstance *goldy_instance_create(void);

// Create a device with a preferred device type.
//
// Returns a pointer to the device, or null on failure.
//
// # Safety
// The instance pointer must be valid.
struct GoldyDevice *goldy_instance_create_device(const struct GoldyInstance *instance,
                                                 enum GoldyDeviceType preferred_type);

// Create a device for a specific adapter ID.
//
// Returns a pointer to the device, or null on failure.
//
// # Safety
// The instance pointer must be valid.
struct GoldyDevice *goldy_instance_create_device_for_adapter(const struct GoldyInstance *instance,
                                                             uint32_t adapter_id);

// Destroy an instance.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_instance_destroy(struct GoldyInstance *instance);

// Get adapter info at the given index.
//
// # Safety
// The instance pointer must be valid.
// The info pointer must point to a valid GoldyAdapterInfo struct.
enum GoldyResult goldy_instance_get_adapter(const struct GoldyInstance *instance,
                                            uint32_t index,
                                            struct GoldyAdapterInfo *info);

// Create a new render pipeline.
//
// Returns a pointer to the pipeline, or null on failure.
//
// # Safety
// All pointers must be valid.
struct GoldyRenderPipeline *goldy_render_pipeline_create(const struct GoldyDevice *device,
                                                         const struct GoldyShaderModule *vertex_shader,
                                                         const struct GoldyShaderModule *fragment_shader,
                                                         const struct GoldyRenderPipelineDesc *desc);

// Destroy a render pipeline.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_render_pipeline_destroy(struct GoldyRenderPipeline *pipeline);

// Get the buffer size in bytes.
//
// # Safety
// The target pointer must be valid.
size_t goldy_render_target_buffer_size(const struct GoldyRenderTarget *target);

// Create a new render target without depth buffer.
//
// Returns a pointer to the render target, or null on failure.
//
// # Safety
// The device pointer must be valid.
struct GoldyRenderTarget *goldy_render_target_create(const struct GoldyDevice *device,
                                                     uint32_t width,
                                                     uint32_t height,
                                                     enum GoldyTextureFormat format);

// Create a new render target with depth buffer.
//
// Returns a pointer to the render target, or null on failure.
//
// # Safety
// The device pointer must be valid.
struct GoldyRenderTarget *goldy_render_target_create_with_depth(const struct GoldyDevice *device,
                                                                uint32_t width,
                                                                uint32_t height,
                                                                enum GoldyTextureFormat color_format,
                                                                enum GoldyDepthFormat depth_format);

// Destroy a render target.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_render_target_destroy(struct GoldyRenderTarget *target);

// Get the render target format.
//
// # Safety
// The target pointer must be valid.
enum GoldyTextureFormat goldy_render_target_format(const struct GoldyRenderTarget *target);

// Check if the render target has a depth buffer.
//
// # Safety
// The target pointer must be valid.
bool goldy_render_target_has_depth(const struct GoldyRenderTarget *target);

// Get the render target height.
//
// # Safety
// The target pointer must be valid.
uint32_t goldy_render_target_height(const struct GoldyRenderTarget *target);

// Read the rendered pixels to a CPU buffer.
//
// # Safety
// The target pointer must be valid.
// The output pointer must point to a buffer of at least `goldy_render_target_buffer_size()` bytes.
enum GoldyResult goldy_render_target_read_to_buffer(const struct GoldyRenderTarget *target,
                                                    uint8_t *output,
                                                    size_t output_size);

// Render commands to the target.
//
// This consumes the encoder.
//
// # Safety
// Both pointers must be valid.
// The encoder is consumed and must not be used after this call.
enum GoldyResult goldy_render_target_render(const struct GoldyRenderTarget *target,
                                            struct GoldyCommandEncoder *encoder);

// Get the render target width.
//
// # Safety
// The target pointer must be valid.
uint32_t goldy_render_target_width(const struct GoldyRenderTarget *target);

// Create a new sampler with the given descriptor.
//
// Returns a pointer to the sampler, or null on failure.
//
// # Safety
// All pointers must be valid.
struct GoldySampler *goldy_sampler_create(const struct GoldyDevice *device,
                                          const struct GoldySamplerDesc *desc);

// Create a sampler with default settings.
//
// Returns a pointer to the sampler, or null on failure.
//
// # Safety
// The device pointer must be valid.
struct GoldySampler *goldy_sampler_create_default(const struct GoldyDevice *device);

// Destroy a sampler.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_sampler_destroy(struct GoldySampler *sampler);

// Get the built-in vertex color 2D shader source.
//
// Returns a pointer to a static null-terminated string.
const char *goldy_shader_builtin_vertex_color_2d(void);

// Create a shader module from Slang source.
//
// Returns a pointer to the shader module, or null on failure.
//
// # Safety
// The device pointer must be valid.
// The source must be a valid null-terminated UTF-8 string.
struct GoldyShaderModule *goldy_shader_create(const struct GoldyDevice *device, const char *source);

// Destroy a shader module.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_shader_destroy(struct GoldyShaderModule *shader);

// Acquire the next frame from the surface.
//
// Returns a pointer to the frame, or null on failure.
//
// # Safety
// The surface pointer must be valid.
struct GoldySurfaceFrame *goldy_surface_acquire(const struct GoldySurface *surface);

// Create a surface from a Win32 HWND.
//
// # Safety
// The device pointer and hwnd must be valid.
struct GoldySurface *goldy_surface_create_win32(const struct GoldyDevice *_device, void *_hwnd);

// Destroy a surface.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_surface_destroy(struct GoldySurface *surface);

// Get the surface format.
//
// # Safety
// The surface pointer must be valid.
enum GoldyTextureFormat goldy_surface_format(const struct GoldySurface *surface);

// Get the frame height.
//
// # Safety
// The frame pointer must be valid.
uint32_t goldy_surface_frame_height(const struct GoldySurfaceFrame *frame);

// Render commands to a frame.
//
// This consumes the encoder.
//
// # Safety
// Both pointers must be valid.
// The encoder is consumed and must not be used after this call.
enum GoldyResult goldy_surface_frame_render(const struct GoldySurfaceFrame *frame,
                                            struct GoldyCommandEncoder *encoder);

// Get the frame width.
//
// # Safety
// The frame pointer must be valid.
uint32_t goldy_surface_frame_width(const struct GoldySurfaceFrame *frame);

// Get the surface height.
//
// # Safety
// The surface pointer must be valid.
uint32_t goldy_surface_height(const struct GoldySurface *surface);

// Present a frame to the surface.
//
// This consumes the frame.
//
// # Safety
// Both pointers must be valid.
// The frame is consumed and must not be used after this call.
enum GoldyResult goldy_surface_present(const struct GoldySurface *surface,
                                       struct GoldySurfaceFrame *frame);

// Resize the surface.
//
// # Safety
// The surface pointer must be valid.
enum GoldyResult goldy_surface_resize(struct GoldySurface *surface,
                                      uint32_t width,
                                      uint32_t height);

// Get the surface width.
//
// # Safety
// The surface pointer must be valid.
uint32_t goldy_surface_width(const struct GoldySurface *surface);

// Create a new texture.
//
// Returns a pointer to the texture, or null on failure.
//
// # Safety
// The device pointer must be valid.
struct GoldyTexture *goldy_texture_create(const struct GoldyDevice *device,
                                          uint32_t width,
                                          uint32_t height,
                                          enum GoldyTextureFormat format,
                                          struct GoldyTextureUsage usage);

// Destroy a texture.
//
// # Safety
// The pointer must be valid and not used after this call.
void goldy_texture_destroy(struct GoldyTexture *texture);

// Get the texture format.
//
// # Safety
// The texture pointer must be valid.
enum GoldyTextureFormat goldy_texture_format(const struct GoldyTexture *texture);

// Get the texture height.
//
// # Safety
// The texture pointer must be valid.
uint32_t goldy_texture_height(const struct GoldyTexture *texture);

// Get the texture width.
//
// # Safety
// The texture pointer must be valid.
uint32_t goldy_texture_width(const struct GoldyTexture *texture);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GOLDY_H */
