//! Rust-authored structured-buffer types lowered to generated Slang structs.

use anyhow::{bail, Result};

/// Portable field types supported by [`GpuType`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GpuFieldType {
    F32,
    U32,
    I32,
    F32x2,
    F32x3,
    F32x4,
    U32x2,
    U32x3,
    U32x4,
    I32x2,
    I32x3,
    I32x4,
    F32x2x2,
    F32x3x3,
    F32x4x4,
}

impl GpuFieldType {
    pub const fn slang_name(self) -> &'static str {
        match self {
            Self::F32 => "float",
            Self::U32 => "uint",
            Self::I32 => "int",
            Self::F32x2 => "float2",
            Self::F32x3 => "float3",
            Self::F32x4 => "float4",
            Self::U32x2 => "uint2",
            Self::U32x3 => "uint3",
            Self::U32x4 => "uint4",
            Self::I32x2 => "int2",
            Self::I32x3 => "int3",
            Self::I32x4 => "int4",
            Self::F32x2x2 => "float2x2",
            Self::F32x3x3 => "float3x3",
            Self::F32x4x4 => "float4x4",
        }
    }

    pub const fn size(self) -> usize {
        match self {
            Self::F32 | Self::U32 | Self::I32 => 4,
            Self::F32x2 | Self::U32x2 | Self::I32x2 => 8,
            Self::F32x3 | Self::U32x3 | Self::I32x3 => 12,
            Self::F32x4 | Self::U32x4 | Self::I32x4 | Self::F32x2x2 => 16,
            Self::F32x3x3 => 36,
            Self::F32x4x4 => 64,
        }
    }
}

/// One field in a Rust-authored GPU struct.
#[derive(Debug, Clone, Copy)]
pub struct GpuField<'a> {
    pub name: &'a str,
    pub offset: usize,
    pub size: usize,
    pub ty: GpuFieldType,
}

/// Exact Rust layout plus enough type information to emit its Slang declaration.
#[derive(Debug, Clone, Copy)]
pub struct GpuType<'a> {
    pub type_name: &'a str,
    pub rust_size: usize,
    pub fields: &'a [GpuField<'a>],
}

/// Generated declaration and matching reflection check.
#[derive(Debug)]
pub(crate) struct GeneratedGpuType {
    pub source: String,
    pub check: super::OwnedLayoutCheck,
}

impl GpuType<'_> {
    /// Emit a Slang struct whose explicit padding reproduces the Rust byte layout.
    pub(crate) fn generate(&self) -> Result<GeneratedGpuType> {
        if self.type_name.is_empty() {
            bail!("GpuType name cannot be empty");
        }

        let mut source = format!(
            "// generated by goldy from Rust `{}`\nstruct {} {{\n",
            self.type_name, self.type_name
        );
        let mut reflected_fields = Vec::new();
        let mut cursor = 0usize;
        let mut pad_index = 0usize;

        for field in self.fields {
            if field.name.starts_with("__goldy_pad") {
                bail!(
                    "GpuType `{}` field `{}` uses reserved prefix `__goldy_pad`",
                    self.type_name,
                    field.name
                );
            }
            if field.offset < cursor {
                bail!(
                    "GpuType `{}` field `{}` overlaps preceding data: offset {} < {}",
                    self.type_name,
                    field.name,
                    field.offset,
                    cursor
                );
            }
            emit_padding(
                &mut source,
                &mut reflected_fields,
                cursor,
                field.offset - cursor,
                &mut pad_index,
                self.type_name,
            )?;

            let expected = field.ty.size();
            if field.size != expected {
                bail!(
                    "GpuType `{}` field `{}` is {} bytes but `{}` requires {}",
                    self.type_name,
                    field.name,
                    field.size,
                    field.ty.slang_name(),
                    expected
                );
            }
            source.push_str(&format!("    {} {};\n", field.ty.slang_name(), field.name));
            reflected_fields.push((field.name.to_string(), field.offset, field.size));
            cursor = field.offset + field.size;
        }

        if cursor > self.rust_size {
            bail!(
                "GpuType `{}` fields extend to {} bytes beyond Rust size {}",
                self.type_name,
                cursor,
                self.rust_size
            );
        }
        emit_padding(
            &mut source,
            &mut reflected_fields,
            cursor,
            self.rust_size - cursor,
            &mut pad_index,
            self.type_name,
        )?;
        source.push_str("};\n");

        Ok(GeneratedGpuType {
            source,
            check: super::OwnedLayoutCheck {
                type_name: self.type_name.to_string(),
                rust_size: self.rust_size,
                rust_fields: reflected_fields,
            },
        })
    }
}

fn emit_padding(
    source: &mut String,
    reflected_fields: &mut Vec<(String, usize, usize)>,
    start: usize,
    byte_count: usize,
    pad_index: &mut usize,
    type_name: &str,
) -> Result<()> {
    if byte_count == 0 {
        return Ok(());
    }
    if byte_count % 4 != 0 {
        bail!(
            "GpuType `{type_name}` has an unrepresentable {byte_count}-byte padding gap at offset {start}; \
             generated Slang padding currently requires 4-byte granularity"
        );
    }
    for word in 0..(byte_count / 4) {
        let name = format!("__goldy_pad{}", *pad_index);
        let offset = start + word * 4;
        source.push_str(&format!("    uint {name};\n"));
        reflected_fields.push((name, offset, 4));
        *pad_index += 1;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_struct_inserts_internal_and_tail_padding() {
        let fields = [
            GpuField {
                name: "position",
                offset: 0,
                size: 12,
                ty: GpuFieldType::F32x3,
            },
            GpuField {
                name: "uv",
                offset: 16,
                size: 8,
                ty: GpuFieldType::F32x2,
            },
        ];
        let generated = GpuType {
            type_name: "Vertex",
            rust_size: 28,
            fields: &fields,
        }
        .generate()
        .unwrap();

        assert!(generated.source.contains("float3 position;"));
        assert!(generated.source.contains("uint __goldy_pad0;"));
        assert!(generated.source.contains("float2 uv;"));
        assert!(generated.source.contains("uint __goldy_pad1;"));
        assert_eq!(
            generated.check.rust_fields,
            vec![
                ("position".into(), 0, 12),
                ("__goldy_pad0".into(), 12, 4),
                ("uv".into(), 16, 8),
                ("__goldy_pad1".into(), 24, 4),
            ]
        );
    }

    #[test]
    fn generated_struct_rejects_subword_padding() {
        let fields = [GpuField {
            name: "value",
            offset: 2,
            size: 4,
            ty: GpuFieldType::U32,
        }];
        let err = GpuType {
            type_name: "Bad",
            rust_size: 6,
            fields: &fields,
        }
        .generate()
        .unwrap_err()
        .to_string();
        assert!(err.contains("4-byte granularity"), "{err}");
    }

    #[test]
    fn generated_struct_rejects_reserved_field_names() {
        let fields = [GpuField {
            name: "__goldy_pad7",
            offset: 0,
            size: 4,
            ty: GpuFieldType::U32,
        }];
        let err = GpuType {
            type_name: "Bad",
            rust_size: 4,
            fields: &fields,
        }
        .generate()
        .unwrap_err()
        .to_string();
        assert!(err.contains("reserved prefix"), "{err}");
    }

    #[test]
    fn derive_emits_tail_padding_from_rust_alignment() {
        #[derive(goldy_derive::GpuType)]
        #[repr(C, align(16))]
        struct TailPadded {
            values: [u32; 3],
        }

        let generated = TailPadded::GPU_TYPE.generate().unwrap();
        assert_eq!(generated.check.rust_size, 16);
        assert!(generated.source.contains("uint3 values;"));
        assert!(generated.source.contains("uint __goldy_pad0;"));
        assert_eq!(generated.check.rust_fields[1], ("__goldy_pad0".into(), 12, 4));
    }

    #[test]
    fn generated_padding_makes_float3_then_float2_match_structured_buffer_stride() {
        use crate::slang::{ShaderTarget, SlangCompiler, SlangStage};
        use crate::types::OptimizationLevel;

        #[derive(goldy_derive::GpuType)]
        #[repr(C)]
        struct PaddedVertex {
            position: [f32; 3],
            #[gpu(padding)]
            _padding: f32,
            uv: [f32; 2],
            light: u32,
        }

        let generated = PaddedVertex::GPU_TYPE.generate().unwrap();
        assert!(
            generated.source.contains("uint __goldy_pad0;"),
            "Rust padding must become reserved generated padding:\n{}",
            generated.source
        );
        let source = format!(
            "{}\nimport goldy_exp;\n\
             [goldy_compute]\n[numthreads(1, 1, 1)]\n\
             void cs_main(BufRO<PaddedVertex> input, Scattered<uint> output, ThreadId id) {{\n\
                 PaddedVertex v = input[id.x];\n\
                 output[id.x] = asuint(v.position.x + v.uv.x) + v.light;\n\
             }}",
            generated.source
        );
        let compiler = SlangCompiler::new().expect("Slang compiler");
        let shader_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("shaders")
            .to_string_lossy()
            .into_owned();

        let result = compiler
            .compile_with_reflection(
                &source,
                ShaderTarget::Spirv,
                &[("cs_main", SlangStage::Compute)],
                &[&shader_path],
                &[("__SPIRV__", "1")],
                &[generated.check],
                OptimizationLevel::None,
            )
            .expect("generated struct must compile and reflect");
        assert_eq!(result.reflection.binding_element_strides[0], Some(28));

        #[cfg(windows)]
        {
            let generated = PaddedVertex::GPU_TYPE.generate().unwrap();
            let result = compiler
                .compile_with_reflection(
                    &source,
                    ShaderTarget::Dxil,
                    &[("cs_main", SlangStage::Compute)],
                    &[&shader_path],
                    &[("__DX12__", "1")],
                    &[generated.check],
                    OptimizationLevel::None,
                )
                .expect("generated struct must compile and reflect for DXIL");
            assert_eq!(result.reflection.binding_element_strides[0], Some(28));
        }
    }

    #[test]
    fn tight_rust_float3_then_float2_is_rejected_by_reflection() {
        #[derive(goldy_derive::GpuType)]
        #[repr(C)]
        struct TightVertex {
            position: [f32; 3],
            uv: [f32; 2],
        }

        let generated = TightVertex::GPU_TYPE.generate().unwrap();
        let compiler = crate::slang::SlangCompiler::new().expect("Slang compiler");
        let shader_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("shaders")
            .to_string_lossy()
            .into_owned();
        let source = format!(
            "{}\nimport goldy_exp;\n[goldy_compute]\n[numthreads(1,1,1)]\n\
             void cs_main(BufRO<TightVertex> input, Scattered<uint> output, ThreadId id) {{\
                 output[id.x] = asuint(input[id.x].uv.x); }}",
            generated.source
        );
        let err = compiler
            .compile_with_reflection(
                &source,
                crate::slang::ShaderTarget::Spirv,
                &[("cs_main", crate::slang::SlangStage::Compute)],
                &[&shader_path],
                &[("__SPIRV__", "1")],
                &[generated.check],
                crate::types::OptimizationLevel::None,
            )
            .unwrap_err()
            .to_string();
        assert!(err.contains("offset Slang 16 vs Rust 12"), "{err}");
    }
}
